### ISSUE TITLE
How to get a unique trace id and operation list over a time period?

### ISSUE THREAD

**Issue by kant777** [grafana/tempo#1104]
How to get a unique trace id and operation list over a time period efficiently?

**Comment by kvrhdn** [comment]
Can you clarify what you mean with operation list?

Tempo supports two query modes right now:
- trace lookup: you specify the trace ID and Tempo returns the full trace
- search: you specify a filter and Tempo will return the most recent traces matching this query.
  - Note: this is **recent search only**, Tempo searches the last 15-30 minutes of traces
  - You can filter on service name, span name, all tags and duration

If you want to search traces long-term, the way to go for now is to log your trace IDs and search your logs.

If you are using the Grafana Agent you can use automatic logging to log incoming traces. See https://grafana.com/docs/tempo/latest/grafana-agent/automatic-logging/

**Comment by kant777** [comment]
I just want to list unique traces over a time interval? does the search return unique traces or all the spans that match the criteria?

**Comment by kvrhdn** [comment]
Search will return a list of (unique) traces with a little bit of metadata (name of the root span, duration, etc.).
You can see an example of the returned JSON here: https://grafana.com/docs/tempo/latest/api_docs/#search

Search does not support specifying a time interval. We are working on this right now, but for now search will always return the most recent traces it finds. It returns up to limit traces at once (which defaults to 20).

**Comment by kant777** [comment]
What indexing mechanism is used underneath by the search API? Bloom filter or inverted index? Does tempo indexes all labels?

**Comment by kvrhdn** [comment]
_Note: search is currently under active development, so the following is likely to be outdated very fast._

Currently (with Tempo v1.2) we extract search data of all the traces we ingest and store them in the search headers. These search headers contain a list of all the traces present in this block with enough metadata to search them directly (so that is trace ID, tags, start time, end time).

Code to extract search data in the distributor: https://github.com/grafana/tempo/blob/v1.2.0/modules/distributor/search_data.go#L25-L28
The search headers are built using flatbuffers: https://github.com/grafana/tempo/blob/v1.2.0/pkg/tempofb/tempo.fbs

We are currently working on a new data format, so this is likely to change.

But in regards to your question: yes, we index all the tags and their values present in a trace.

**Comment by kvrhdn** [comment]
I'm going to close this issue, I think your original problem has been addressed. But feel free to add comments here (I'll get notifications) or reach out to us in the community Slack 🙂

**Comment by kant777** [comment]
Thanks. which slack channel?

**Comment by kvrhdn** [comment]
The Grafana community slack: https://slack.grafana.com/
We have a channel #tempo.
