### ISSUE TITLE
Increase protection from large traces

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1133]
**Is your feature request related to a problem? Please describe.**
It is relatively easy to push traces larger than the configured limit into Tempo. These very large traces can break compactors, the query path, and sometimes ingesters.

**Describe the solution you'd like**
It is impossible to completely protect ourselves from traces exceeding the configured limit, but there is room for improvement. Currently as soon as a trace is removed from the active traces map we no longer track trace size and it is possible to start pushing to the trace again. Proposed:
- Maintain a `map[uint32]struct{}` of trace hashes that had refused spans due to trace too large
- Check the map on write and reject any hashes found with TRACE_TOO_LARGE
- Clear the map when the head block is cut

**Describe alternatives you've considered**

**Additional context**
@annanay25 I think you were considering similar functionality. If you have any thoughts please include them here.

**Comment by annanay25** [comment]
We were tracking some options here: https://github.com/grafana/tempo/issues/976 

But that was focused on protecting compactors, good call on "moving it up" to the ingesters - If we can reject the trace at ingestion it will protect all downstream components

**Comment by mdisibio** [comment]
More options:
* Compactors delete traces larger than configurable threshold.  These mega/gigatraces aren't queryable anyway... acceptable data loss?
* Compactors skip over/don't combine traces larger than configurable threshold. Some small code structure changes needed as several things require a single output `[]byte` (`ObjectCombiner` interface, deduping iterator, etc).  Traces still aren't queryable, so the problem is not fully solved.
* Performance improvements to `model.CombineObjects`. I.e. the overall design remains, just improve stability/performance around large traces.  A couple changes:  only scan span IDs once per input, only sort final result once.

**Comment by joe-elliott** [comment]
This was fixed in #1199.
