### ISSUE TITLE
Support integration from Kiali so Tempo will fully support Istio

### ISSUE THREAD

**Issue by stevehipwell** [grafana/tempo#1139]
**Is your feature request related to a problem? Please describe.**
I can't currently use Tempo for Istio tracing if I want to use the Kiali dashboard (see [kiali/kiali#4278](https://github.com/kiali/kiali/issues/4278)); and the Kiali dashboard is the idiomatic way to observe Istio.

**Describe the solution you'd like**
I'd like Kiali to be able to query Tempo and navigate to the correct Grafana tempo view.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kvrhdn** [comment]
Hi, thanks for reaching out! I'll take a detailed read through the thread and reply there as well.

What I can already share:

If Kiali supports querying Jaeger, you can use the `tempo-query` component to act as a Jaeger proxy in front of Tempo. We don't have a lot of documentation on this because we are _kind of_ phasing out this component (it was originally designed to work with Grafana before we had a native datasource) but it should still work fine (including search).

- This docker-compose example runs both Tempo and tempo-query: [example/docker-compose/grafana7.4](https://github.com/grafana/tempo/tree/main/example/docker-compose/grafana7.4)
tempo-query is running on port 16686, so you can navigate there directly to get the Jaeger UI or point Kiali to port 16686.
- Our Jsonnet library and Helm chart run tempo-query as sidecar of the query-frontend. So if you use those you might just have to open the right port.

Regarding the query API: we have a pretty simple API that returns traces in the OpenTelemetry format (JSON or protobuf).
API docs: https://grafana.com/docs/tempo/latest/api_docs/#query
OpenTelemetry format: https://github.com/open-telemetry/opentelemetry-proto/tree/main/opentelemetry/proto/trace/v1

If Kiali would like to add querying support for more backends, adding support for OpenTelemetry might be a good idea as the tracing ecosystem is converging on OpenTelemetry. It's possible to convert most common tracing formats into OpenTelemetry right now.

**Comment by kvrhdn** [comment]
Hi, I've responded in the Kiali issue as well. I'm going to close this issue because there is nothing to do right now. Tempo is just a backend, Kiali should update its client to support Tempo. If there is anything Tempo can do to simplify integration with Kiali feel free to open a new feature request.

If you have any questions you can also reach out through Slack or our community forum. You can find links here: https://grafana.com/docs/tempo/latest/community/

And finally, if you get Kiali working with Tempo please let us know! We love seeing people use Tempo out there 🙂

**Comment by muhammadn** [comment]
There is actually *something* we can do about it. I hate to say this because we have so much bureaucracy around rather than just making things work and be happy chugging along. 

Everyone is pointing to OTel but OTel is still not doing anything about it. We are depending and asking too much for OTel and so much decision making is given to one entity. 

For a company like Grafana that is huge, there should be something that Grafana could do to *at least* make it easier for someone to understand on how to read Tempo's API, rather than just pointing to a [protobuf](https://grafana.com/docs/tempo/latest/api_docs/#query) file in Tempo's documentation and expecting someone to understand it and build something around that API and that's pretty basic and we need a "feature request" for grafana to hear us out for better documentation. 

I have looked at tempo-query and you said it's going to deprecated. What choice do we have? 

That said, even looking at tempo's API make me want to puke. search is still experimental and that's the only *meaningful* API that i've come across that makes sense on integrating with kiali.

So i tell myself, screw all this bullshit and write the code so my team can do their [work](https://github.com/muhammadn/jaeger-tempo).

**Comment by kvrhdn** [comment]
I understand you are frustrated about _something_, but honestly barging into an issue and just complaining about our docs not being unclear isn't very constructive. Can you clarify what you are trying to achieve?

> There is actually _something_ we can do about it. I hate to say this because we have so much bureaucracy around rather than just making things work and be happy chugging along.
> 
> Everyone is pointing to OTel but OTel is still not doing anything about it. We are depending and asking too much for OTel and so much decision making is given to one entity.

We are not really asking anything of OpenTelemetry in this issue. Tempo has adapted the OpenTelemetry Line Protocol (OTLP) as data format. OTel has pushed this forward as standard and we adopted it for several reasons. We support ingesting different formats, but querying is only OTLP.

If Kiali wants to support Tempo as backend, they only have to implement our query API since we already support ingesting Jaeger. There is no standardised OTel query API and I deem it unlikely one will show up unless consumers of such an API come together and list their needs and requirements.

> For a company like Grafana that is huge, there should be something that Grafana could do to _at least_ make it easier for someone to understand on how to read Tempo's API, rather than just pointing to a [protobuf](https://grafana.com/docs/tempo/latest/api_docs/#query) file in Tempo's documentation and expecting someone to understand it and build something around that API and that's pretty basic and we need a "feature request" for grafana to hear us out for better documentation.

The .proto file you linked to is the exact definition of the data format used throughout Tempo. You can generate a client library for this format in most programming languages, see https://developers.google.com/protocol-buffers.
While it might not be the easiest to read, once you get the hang of it it should be very straightforward. In fact, you don't even have to read it since you can just generate a library for it in your preferred language.

We didn't spend time documenting every field in this format since it's already documented in the OTel specification. And by pointing upstream we ensure the linked .proto file is always up-to-date.

> I have looked at tempo-query and you said it's going to deprecated. What choice do we have?

We originally built tempo-query since older versions of Grafana did not yet support Tempo natively. To still support Grafana <7.5, tempo-query provides a Jaeger-compatible API in front of Tempo. This was only intended as a temporary solution and as the Tempo API evolves this bridge will become more difficult to maintain. For instance, we are currently working on a query language for Tempo (traceQL) which will have features that do not exist in Jaeger and will be difficult to map.
At some point we will have to cut our losses and completely remove the component from Tempo.

> That said, even looking at tempo's API make me want to puke. search is still experimental and that's the only _meaningful_ API that i've come across that makes sense on integrating with kiali.

I'm sorry our docs make you nauseous. Can you clarify what is causing this or maybe provide suggestion? We are eager to improve our docs.

the search API is currently marked experimental because we will soon be doing changes to it as we introduce traceQL. While the API in practice didn't change since it's introduction in Tempo v1.3 we marked it experimental to be prudent.

> So i tell myself, screw all this bullshit and write the code so my team can do their [work](https://github.com/muhammadn/jaeger-tempo).

Again, please let us know what you are trying to achieve and we can try to work with you. I'm interested to know what the goal is of jaeger-tempo and how it will interoperate with Tempo.

**Comment by muhammadn** [comment]
Sorry for not being unconstructive but all we have is discussions that ends up with no results. It's not just me but many others are equally frustrated with things not moving at all.

> We are not really asking anything of OpenTelemetry in this issue. Tempo has adapted the OpenTelemetry Line Protocol (OTLP) >as data format. OTel has pushed this forward as standard and we adopted it for several reasons. We support ingesting different >formats, but querying is only OTLP.

>If Kiali wants to support Tempo as backend, they only have to implement our query API since we already support ingesting >Jaeger. There is no standardised OTel query API and I deem it unlikely one will show up unless consumers of such an API come >together and list their needs and requirements.

There are other people **outside** of Grafana that had been trying to [get](https://github.com/open-telemetry/oteps/issues/193) things moving but i believe Grafana could be involved in having the voice of getting suggestions into OTel as this would improve tempo, so we can start working on something.

>The .proto file you linked to is the exact definition of the data format used throughout Tempo. You can generate a client library >for this format in most programming languages, see https://developers.google.com/protocol-buffers.
>While it might not be the easiest to read, once you get the hang of it it should be very straightforward. In fact, you don't even >have to read it since you can just generate a library for it in your preferred language.

>We didn't spend time documenting every field in this format since it's already documented in the OTel specification. And by >pointing upstream we ensure the linked .proto file is always up-to-date.

Documentation are the the important piece of information that a developer who is writing an interface to an API would need. It requires being meticulous and detail about what it is about.

For example, in the trace endpoint, there should also be a JSON response detail, so anyone who have no knowledge of protobuf would have some idea of how the JSON result is like, at least with a link to OTel. Not everyone deal with protobuf, they deal with JSON and it can cause a major friction to start off writing interfaces with Tempo's API.

>We originally built tempo-query since older versions of Grafana did not yet support Tempo natively. To still support Grafana <7.5, tempo-query provides a Jaeger-compatible API in front of Tempo. This was only intended as a temporary solution and as >the Tempo API evolves this bridge will become more difficult to maintain. For instance, we are currently working on a query >language for Tempo (traceQL) which will have features that do not exist in Jaeger and will be difficult to map.
>At some point we will have to cut our losses and completely remove the component from Tempo.

I have a view that jaeger-query was just part of EEE (Embrace, Extend and Extinguish) part of interoperability of tempo with jaeger, despite tempo-query's shortcomings. But i may be wrong but that's how i feel.

As an SRE, it's critical for all the components to work, discussions can take time and it's no excuse for me to take that as an answer and in my part, is to take action to solve the problem.

>the search API is currently marked experimental because we will soon be doing changes to it as we introduce traceQL. While >the API in practice didn't change since it's introduction in Tempo v1.3 we marked it experimental to be prudent.

Yes. I just hope that traceQL would be better than the current solution. But it would be better if you can have something similar like an API Spec that makes it easier for developers to generate boilerplate code and write that interface to Tempo's API. This is something that i had discussed with my colleague and was his concern.

>Again, please let us know what you are trying to achieve and we can try to work with you. I'm interested to know what the goal is >of jaeger-tempo and how it will interoperate with Tempo.
`jaeger-tempo` is actually `tempo-query` and giving `tempo-query` some ❤️ it needs. Documentation, documentation and documentation. 

Gave it binary releases and simplify it with a docker image. (which is not released by tempo's repo and needs to be built and configured)

From what i see from your comments, in here or other repositories, you never did once mentioned `tempo-query` is a Jaeger plugin (which it is).. You only mentioned it is something like an "interface" to tempo that kiali can consume. While i agree that it has it's shortcomings but it does it's job. That's the important thing i need to ensure as an SRE. 

But this is a bandaid and a temporary workaround until i can find a solution. I do not wish to wait for OTel because they are unresponsive, mostly - if not all.

**Comment by aranair** [comment]
> * This docker-compose example runs both Tempo and tempo-query: [example/docker-compose/grafana7.4](https://github.com/grafana/tempo/tree/main/example/docker-compose/grafana7.4)
>   tempo-query is running on port 16686, so you can navigate there directly to get the Jaeger UI or point Kiali to port 16686.

@kvrhdn - I am testing tempo-query (port 16686 / http) together w Kiali as a workaround but it seems like tempo-query only serves the jaeger frontend ui and not the api on that port, is this accurate? (I believe kiali expects the api)
