### ISSUE TITLE
Hedge request metrics goroutine/ticker leak

### ISSUE THREAD

**Issue by cyriltovena** [grafana/tempo#1143]
https://github.com/grafana/tempo/blob/5124375ebfb128a9e698c81934a4d81b2887f299/tempodb/backend/instrumentation/hedged_requests.go#L26

This function creates a ticker and a go routine, without exit conditions, depending on the usage( e.g create multiple client and throwing them away) this will cause leaking them both.

**Comment by joe-elliott** [comment]
As its written this does not currently leak resources because a single instance of this client is created per instance of Tempo that lasts the lifetime of the process. 

But agree it would be an improvement to clean this up as its a nasty "gotcha" if we change the way we use the clients. Thanks for the issue.

**Comment by cyriltovena** [comment]
In Loki we'll go down another route which might be useful for you too. I'll share more when we got it.

**Comment by cyriltovena** [comment]
and I agree nothing urgent for tempo, just wanted to get an issue for it.
