### ISSUE TITLE
Run local docker-compose example fail.

### ISSUE THREAD

**Issue by Oseenix** [grafana/tempo#1280]
**Describe the bug**

The following local example can't work. 
https://github.com/grafana/tempo/tree/main/example/docker-compose/local
The 1-3 steps works, but when navigating to [Grafana](http://localhost:3000/explore) in the 4th step, the query will meet "Query error".
Datasource test fail for both `Prometheus` and `Tempo`

**To Reproduce**
1.   cd /path-to-tempo-src/example/docker-compose/local
2.  docker-compose up -d
3.  docker-compose logs -f synthetic-load-generator
4.  navigating to [Grafana](http://localhost:3000/explore) 

**Expected behavior**

when navigating to [Grafana](http://localhost:3000/explore),  we can query data.

**Environment:**
 - Infrastructure: laptop/macos monterey
 - Deployment tool: Docker Compose version v2.2.3/Docker version 20.10.12, build e91ed57

**Comment by zalegrala** [comment]
Hi, thanks for raising the issue.  I tried this out just now from the most recent `main` and this looks to work for me.  The datasource does indeed fail to "test", but I think this is related to an older version of Grafana using the wrong API to determine if Tempo is healthy.  We get a 404 back, so we at least know that Grafana has been able to reach the service.

![image](https://user-images.githubusercontent.com/88330524/153440896-77c9809e-cebc-4278-b463-3c0d64b7afaf.png)

**Comment by Oseenix** [comment]
Hi, Thank you for your support. I also use the most recent `main` just now.
<img width="823" alt="Screenshot 2022-02-10 at 11 40 55 PM" src="https://user-images.githubusercontent.com/8219928/153442833-305ee6f0-10b0-4746-94d2-4f79ad100034.png">
<img width="1534" alt="Screenshot 2022-02-10 at 11 41 25 PM" src="https://user-images.githubusercontent.com/8219928/153442858-7b493729-18ed-4a6a-bec7-ae61af7107b0.png">

Is there any steps I can try to find out the problem.

**Comment by Oseenix** [comment]
> One thing to double check is that the query was issued to Tempo. You can do this by checking the tempo logs. For example, I see this when I issue the query through grafana.
> 
> ```
> level=info ts=2022-02-10T16:09:25.534800918Z caller=tempodb.go:348 org_id=single-tenant msg="searching for trace in block" findTraceID=0000000000000000edb91ae9cc227a24 block=9c4a8109-9f58-4ff8-8f3c-7569672af3a9 found=false
> level=info ts=2022-02-10T16:09:25.539374836Z caller=tempodb.go:348 org_id=single-tenant msg="searching for trace in block" findTraceID=0000000000000000edb91ae9cc227a24 block=1936e207-4e27-4f29-97ee-8fe2ec5a84ec found=false
> level=info ts=2022-02-10T16:09:25.540393284Z caller=tempodb.go:348 org_id=single-tenant msg="searching for trace in block" findTraceID=0000000000000000edb91ae9cc227a24 block=5d42a6eb-4d61-48f5-8bb3-867d680c0abf found=false
> level=info ts=2022-02-10T16:09:25.540920213Z caller=tempodb.go:348 org_id=single-tenant msg="searching for trace in block" findTraceID=0000000000000000edb91ae9cc227a24 block=243c8dbb-4fba-4ac2-94ca-13ac7c334a35 found=false
> level=info ts=2022-02-10T16:09:25.5439791Z caller=tempodb.go:348 org_id=single-tenant msg="searching for trace in block" findTraceID=0000000000000000edb91ae9cc227a24 block=7cc63413-6bb9-4f37-bca7-baa0a594d08f found=false
> level=info ts=2022-02-10T16:09:25.544383291Z caller=tempodb.go:348 org_id=single-tenant msg="searching for trace in block" findTraceID=0000000000000000edb91ae9cc227a24 block=cd5e75dd-e0ee-412b-909f-01fa38ec7514 found=false
> level=info ts=2022-02-10T16:09:25.54512089Z caller=handler.go:118 tenant=single-tenant method=GET traceID=1b678cb4031ea9cc url=/api/traces/edb91ae9cc227a24 duration=17.222556ms response_size=1580 status=200
> ```

from the output of 
```
 docker-compose logs -f tempo
```
It seems that the query is not issued to Tempo

```
local-tempo-1  | level=info ts=2022-02-15T06:36:12.3169033Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
local-tempo-1  | level=info ts=2022-02-15T06:36:12.3171698Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
local-tempo-1  | level=info ts=2022-02-15T06:36:12.3637311Z caller=flush.go:244 msg="completing block" userid=single-tenant blockID=09db4a7d-9c95-42c6-8620-33c5a0dad717
local-tempo-1  | level=info ts=2022-02-15T06:36:12.6617833Z caller=flush.go:251 msg="block completed" userid=single-tenant blockID=09db4a7d-9c95-42c6-8620-33c5a0dad717 duration=298.5515ms
local-tempo-1  | level=info ts=2022-02-15T06:36:12.6663332Z caller=flush.go:300 msg="flushing block" userid=single-tenant block=09db4a7d-9c95-42c6-8620-33c5a0dad717
local-tempo-1  | level=info ts=2022-02-15T06:36:12.8156823Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
local-tempo-1  | level=info ts=2022-02-15T06:36:12.8158143Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
local-tempo-1  | level=info ts=2022-02-15T06:36:13.3188688Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
local-tempo-1  | level=info ts=2022-02-15T06:36:13.3198583Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
local-tempo-1  | level=info ts=2022-02-15T06:36:13.8176464Z caller=compactor.go:98 msg="starting compaction cycle" tenantID=single-tenant offset=0
local-tempo-1  | level=info ts=2022-02-15T06:36:13.8181789Z caller=compactor.go:104 msg="compaction cycle complete. No more blocks to compact" tenantID=single-tenant
```

**Comment by Oseenix** [comment]
when I log in to Grafana docker, it seems that it inherits the network proxy settings from the local host.
```
/usr/share/grafana $ wget http://tempo:3200
Connecting to 192.168.35.10:8118 (192.168.35.10:8118)

~ $ echo $http_proxy
http://192.168.35.10:8118
~ $ echo $https_proxy
http://192.168.35.10:8118
```

**Comment by zalegrala** [comment]
Perhaps `unset` those variables before `docker-compose up` and see how it goes.  I looked briefly at the image stack and didn't see those `ENV` mentioned in the containers.

**Comment by Oseenix** [comment]
> Perhaps `unset` those variables before `docker-compose up` and see how it goes. I looked briefly at the image stack and didn't see those `ENV` mentioned in the containers.

I am sure that there is no $http_proxy or $https_proxy in the host environment before `docker-compose up`.
In addition, I set $http_proxy / $https_proxy to blank in docker-compose.yml
```
  grafana:
    image: grafana/grafana:8.1.6
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - http_proxy=
      - https_proxy=
```
In `Grafana` docker container, they are unset,
```
/usr/share/grafana $ echo $http_proxy

/usr/share/grafana $ echo $https_proxy

/usr/share/grafana $
```

but it steal connect to the proxy:
```
local-grafana-1  | t=2022-02-16T02:14:25+0000 lvl=eror msg="Metric request error" logger=context userId=0 orgId=1 uname= error="failed get to tempo: Get \"http://tempo:3200/api/traces/\": proxyconnect tcp: dial tcp 192.168.35.10:8118: i/o timeout" remote_addr=172.26.0.1
local-grafana-1  | t=2022-02-16T02:14:25+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/ds/query status=500 remote_addr=172.26.0.1 time_ms=10011 size=34 referer=http://localhost:3000/explore
```

so, maybe it is a problem related to the Docker/docker-compose on macOS.

**Comment by Oseenix** [comment]
Finally, find out the problem, it's the proxy configuration in ~/.docker/config.json. Thank you for your help. @zalegrala

**Comment by zalegrala** [comment]
Oh good, I'm glad you were able to get it working.

**Comment by zalegrala** [comment]
Hi @htbmw, I'm not quite clear what is being asked.  The `wget` binaries are useful for testing, but are not invoked by Tempo, so should not play a role here outside of testing if the HTTP endpoint is available from within the container.  You mention that you would like the containers to have outside access, but do you mean ingress or egress?  If the listening port for Tempo is exposed to the network, it should be reachable and the busybox binaries shouldn't play a role here.  Could you clarify your ask?  It might be worth opening a separate issue since the original request here was resolved.

**Comment by htbmw** [comment]
Hi @zalegrala,

To be honest, this is not the right repo to discuss my question as I think it is actually related to grafana and not Tempo.
I merely commented here because the issue described in this thread was exactly what I experienced.
I later realized the actual problem is with the grafana image which is based on an alpine image with busybox.
So basically the problem is that grafana cannot reach Tempo.
I don't know what Grafana uses, but wget was merely an example of a command I tested in a shell of the grafana container to prove the point regarding the limited support for proxies in busybox.

I further proved this by cloning the grafana repo, changing the Dockerfile to use ubuntu:20.04 base image instead of alpine and built a new custom image.
Deploying this custom-built image on a local environment behind a proxy works perfectly, unlike the official released Grafana image based on alpine and busybox.

**Comment by zalegrala** [comment]
Fair enough.  I'm not sure how to help the situation where there is a proxy between grafana and tempo.  The busybox wget binaries are probably just built without the proxy support, which isn't necessarily representative of the traffic or support in grafana for use of the proxy environment variables.

I suppose what I'm thinking is that if you have a specific architecture, we should discuss those specifically since the busybox binaries aren't going to affect the grafana/tempo binaries that are built in the container.  Feel free to ask questions in our community slack or start a discussion on the relevant repos.

**Comment by htbmw** [comment]
Hi @zalegrala ,
Thanks for your replies. 
Since the issue/discussion is closed anyway, there is nothing to do further.
I will continue using my custom built image.
