### ISSUE TITLE
unknown encoding v2. Supported encodings [v1]

### ISSUE THREAD

**Issue by minghsu0107** [grafana/tempo#1283]
**Describe the bug**

Error during compaction cycle occurs repeatedly: `unknown encoding v2. Supported encodings [v1]`. However, compaction is completed successfully, and files are uploaded successfully on my object storage.  

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/50090692/153747939-b2b0c1be-a075-4b37-a995-c3316e584193.png">

**To Reproduce**
1. Start Tempo with object storage backend configured
2. View tempo compactor logs

**Expected behavior**

No such error occurs.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm
 - Tempo image version: 1.3.1

**Comment by joe-elliott** [comment]
This is very odd. Are any of your components running newer images of Tempo? 1.3.1 did not have support for `v2` so that error message is correct, but nothing should be making `v2` blocks except for images cut after 1.3.1.

1.3.1:
https://github.com/grafana/tempo/blob/5684f8cb6bba2a503da8568f60edfbde06909b6a/pkg/model/encoding.go#L38-L45

tip of main:
https://github.com/grafana/tempo/blob/fe9a5e923e07b9bac533720921ec6623be70a3b2/pkg/model/object_decoder.go#L36-L45

**Comment by minghsu0107** [comment]
Thank you for the reply. After double-checking I found out that the ingester image is not `1.3.1` but `latest`.
