### ISSUE TITLE
 failed to mark block compacted and poll blocklist 

### ISSUE THREAD

**Issue by hwu-talendbj** [grafana/tempo#1372]
**Describe the bug**
Hi, I have some recurring error events from Tempo Compactor stating " failed to mark block compacted" and "failed to poll blocklist". Both of them are due to “Description=404 The specified blob does not exist”, but somehow I don't how to troubleshoot it.

This happens only in our Azure environments, where Tempo is configured to leverage Azure Blob Storage as a long term storage.

**To Reproduce**

1. Start Tempo 1.3.0 with Azure Blob Storage configured
2. Wait for a compaction cycle with proper blocks to compact & store

**Expected behavior**
Compacted blocks are successfully pushed to azure Blob Storage & then marked as compacted without errors.

**Environment:**

- Infrastructure: Kubernetes, Azure Blob Storage
- Deployment tool: Helm using the official Helm chart version 0.15.1

**Additional Context**

Log event:

  |   | 2022-04-08 14:36:51 | failed to mark block compacted during retention
-- | -- | -- | --
  |   | 2022-04-08 14:31:53 | failed to poll blocklist. using previously polled lists
  |   | 2022-04-08 14:06:51 | failed to mark block compacted during retention
  |   | 2022-04-08 13:36:51 | failed to mark block compacted during retention
  |   | 2022-04-08 11:06:51 | failed to mark block compacted during retention
  |   | 2022-04-08 10:06:51 | failed to mark block compacted during retention
  |   | 2022-04-08 09:06:51 | failed to mark block compacted during retention
  |   | 2022-04-08 08:36:51 | failed to mark block compacted during retention
  |   | 2022-04-08 08:31:53 | failed to poll blocklist. using previously polled listsShow context
  |   | 2022-04-08 08:06:51 | failed to mark block compacted during retention
  |   | 2022-04-08 07:36:51 | failed to mark block compacted during retention

error.message 

```

reading storage container: cannot download blob, name: single-tenant/57f*****-fd0a-4616-90ea-c6b8443f43b0/meta.json: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /drone/src/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42 ===== RESPONSE ERROR (ServiceCode=BlobNotFound) ===== Description=The specified blob does not exist. RequestId:53ccf977-101e-005b-7e12-4b0ff4000000 Time:2022-04-08T06:31:52.1394707Z, Details:     Code: BlobNotFound    GET https://tempo****************.blob.core.windows.net/tempo/single-tenant/57f******-fd0a-4616-90ea-c6b8443f43b0/meta.json?timeout=61    Authorization: REDACTED    User-Agent: [Tempo Azure-Storage/0.13 (go1.17.6; linux)]    X-Ms-Client-Request-Id: [0ae85a73-43ea-4977-7af1-44855e3c5cf7]    X-Ms-Date: [Fri, 08 Apr 2022 06:31:52 GMT]    X-Ms-Range: [bytes=0-401]    X-Ms-Version: [2019-12-12]    --------------------------------------------------------------------------------    RESPONSE Status: 404 The specified blob does not exist.    Content-Length: [215]    Content-Type: [application/xml]    Date: [Fri, 08 Apr 2022 06:31:51 GMT]    Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]    X-Ms-Client-Request-Id: [0ae85a73-43ea-4977-7af1-44855e3c5cf7]    X-Ms-Error-Code: [BlobNotFound]    X-Ms-Request-Id: [53ccf977-101e-005b-7e12-4b0ff4000000]    X-Ms-Version: [2019-12-12]

```

**Comment by hwu-talendbj** [comment]
it seems that block compaction itself is fine, here is the status from Grafana
![image](https://user-images.githubusercontent.com/51224998/162685392-86003236-2d31-4614-b1cd-b2579b45bec7.png)

**Comment by mdisibio** [comment]
We see the error `failed to mark block compacted during retention` sometimes too, and agree that it does not prevent compaction overall, as long as they are not too many.   Generally our understanding is that happens when two compactors choose the same block, and the first one to finish marks the block as compacted. When the second one finishes, it has this error because `meta.json` has already been renamed to `meta.compacted.json`.

A few things to check:
* Are your compactors crashing or restarting frequently?
* Can you check the compactor ring status and see if there are any unhealthy entries?
* An edge case:  is anything else deleting blocks from the bucket?  If something has deleted the block while Tempo is trying to compact it.

The `failed to poll blocklist` error we also get occasionally but for a different reason `operation was canceled`.  Not sure about your error... Polling the blocklist is expected to handle cases where `meta.json` doesn't exist (compacted blocks renamed as described above), so it shouldn't be a problem.  Will review the error handling code.

**Comment by hwu-talendbj** [comment]
@mdisibio, Thanks for your quick response.  So why do we have the case that two compactors choose the same block?  I only can see one compactor Pod running in our K8S cluster , and Compared with AWS S3 bucket, 

- Are your compactors crashing or restarting frequently?
compactors  are good, no restarting frequently

- Can you check the compactor ring status and see if there are any unhealthy entries?
no unhealthy entries

- An edge case: is anything else deleting blocks from the bucket? If something has deleted the block while Tempo is trying to compact it.
it seems not

**Comment by mdisibio** [comment]
Thanks for checking those things.  In reviewing our logs for `failed to mark block compacted during retention` I can confirm that we also see it within 1 compactor.  In our case, the same pod successfully marks a block compacted, and then fails again a few minutes later on the same block.    It looks a race condition between retention and polling because both execute at the the same interval.   If retention is able to execute twice before the next polling, the block is retained twice.  One possible fix is to update the in-memory block list after retaining the block, to move it from active blocks to compacted blocks here : https://github.com/grafana/tempo/blob/main/tempodb/retention.go#L55  We already do the same after compaction for the same reason:  https://github.com/grafana/tempo/blob/main/tempodb/compactor.go#L175.   This should be an easy fix. For now I would say it is ok to ignore those messages.


Regarding `failed to poll blocklist` can you confirm the entire error that is logged?  Saw that `reading storage container: cannot download blob, name: single-tenant/57f*****-fd0a-4616-90ea-c6b8443f43b0/meta.json....` was posted but making sure.  I am suspecting the error handling logic here:  https://github.com/grafana/tempo/blob/main/tempodb/backend/azure/azure.go#L310    It translates certain errors into `backend.ErrDoesNotExist` so that the upstream logic in Tempo can handle gracefully. I.e. if we check for meta.json but instead meta.compacted.json exists, this is expected.     I suspect this logic is not right because your error message above contains `(ServiceCode=BlobNotFound)` but also starts with `reading storage container:`. This looks like it should have been translatable to `ErrDoesNotExist` but wasn't.

**Comment by hwu-talendbj** [comment]
Hi, thanks for the detailed explanation,  that is very helpful. 
Yes, I confirmed that the entire error that is `reading storage container: cannot download blob, name: single-tenant/57f*****-fd0a-4616-90ea-c6b8443f43b0/meta.json....` I posted above

**Comment by joe-elliott** [comment]
Thanks for the issue! The two linked PRs should clean up any issues you are seeing. If, after upgrading, you continue to have similar problems please feel free to reopen.

**Comment by hwu-talendbj** [comment]
@mdisibio @joe-elliott   thanks for helping, we have upgraded tempo to the new version, and the "failed to mark block compacted" errors are gone now.  The Ring Status is good as well. 
But we still can see  sustained polling issues and `failed to clear compacted block during retention` issues 

![image](https://user-images.githubusercontent.com/51224998/171340082-044e4390-ad73-4654-9ca5-d5cdd6c63b16.png)

regarding `failed to poll blocklist`, the error msg detail is here 

`reading storage container: Head "https://tempoe4c1358e882b.blob.core.windows.net/tempo/single-tenant/d8aafc48-5796-4221-ac0b-58e001d18515/meta.compacted.json?timeout=61": dial tcp: lookup tempoe4c1358e882b.blob.core.windows.net on 10.0.0.10:53: dial udp 10.0.0.10:53: operation was canceled`

regarding `failed to clear compacted block during retention`, the error msg detail is here 

`error deleting blob, name: single-tenant/*******************/data: Delete "https://tempoe******.blob.core.windows.net/tempo/single-tenant/5b1ab746-fee7-409c-944d-1c1d5ba7a70e/data?timeout=61": dial tcp: lookup tempoe******.blob.core.windows.net on 10.0.0.10:53: dial udp 10.0.0.10:53: operation was canceled`

but I check the blob is not existed, not sure why it complains this
