### ISSUE TITLE
Span metrics: use concise span_kind and span_status label values

### ISSUE THREAD

**Issue by kvrhdn** [grafana/tempo#1429]
**Is your feature request related to a problem? Please describe.**
Span metrics generated by the metrics-generator contain a `span_kind` label. This label contains values like `SPAN_KIND_CLIENT`, `SPAN_KIND_UNSPECIFIED`,... This is a mouthful and doesn't match with the specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind The specification uses just `CLIENT`, `UNSPECIFIED`,...

Similarly for `span_status`, we emit values like `STATUS_CODE_UNSET` and `STATUS_CODE_ERROR`.

**Describe the solution you'd like**
The `SPAN_KIND_` and `STATUS_CODE_` prefix is unnecessary and clutters the screen. It's also shared between all values and carries little extra information. The user should already have enough context from the label name. I suggest dropping it and writing a more concise value (just `CLIENT`, `UNSPECIFIED` or `UNSET`, `ERROR`).

**Describe alternatives you've considered**
We can keep using the current label values.

**Additional context**
We are writing these values here: 
https://github.com/grafana/tempo/blob/eb8a72c68dc9fe8c784ed4d508f0298b2173faba/modules/generator/processor/spanmetrics/spanmetrics.go#L77

We can probably make this a bit nicer by formatting it before writing it.

**Comment by joe-elliott** [comment]
100% agree with the proposed changes here. However, I believe that these values came from the original otel collector processor:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanmetricsprocessor

Does this change impact any of the Grafana visualization functionality we are building around these metrics? I wonder if we can get the collector to make similar changes so that Tempo can stay consistent with the Agent and the Collector.
