### ISSUE TITLE
Implement configuration option for the querier to only hit the ingesters based on the trace id hashes instead of all healthy ingesters.

### ISSUE THREAD

**Issue by sagarwala** [grafana/tempo#1477]
**Is your feature request related to a problem? Please describe.**
This is a feature request for Trace by ID API call on Query Frontend. We understand that each call gets sharded and parallel requests are sent to Querier and Ingester to fetch the trace based on the ID, but as per the [code](https://github.com/grafana/tempo/blob/main/modules/querier/querier.go#L194) , are we making a call to all healthy ingesters in the ring. 

**Describe the solution you'd like**
This can lead to issues with fetch, even though one of the ingesters are unhealthy(for RF=1), we will not be able to query the ingesters as it will fail with _Too many unhealthy replicas_ error. We watch to fetch the ingester instance based on the hash of trace id (how we find out the ingester instance during distributor writes by using the filter on [ringstrategy](https://github.com/grafana/tempo/blob/35d7e668d7c8466e372f99edaa99007be5eb2b03/vendor/github.com/grafana/dskit/ring/batch.go#L58)

**Describe alternatives you've considered**
We can increase the RF to increase failure tolerance but that has an associated cost.

cc: @bikashmishra100 , @ashwinidulams

**Comment by bikashmishra100** [comment]
Along the same lines, similar to EventuallyConsistentStrategy https://github.com/grafana/tempo/blob/35d7e668d7c8466e372f99edaa99007be5eb2b03/pkg/ring/ring.go#L39, we want to be able to use ignoreUnhealthyInstancesReplicationStrategy https://github.com/grafana/tempo/blob/35d7e668d7c8466e372f99edaa99007be5eb2b03/vendor/github.com/grafana/dskit/ring/replication_strategy.go#L73. Shall we make it configurable ?

**Comment by joe-elliott** [comment]
I'm not sure I'd look at the `EventuallyConsistentStrategy` too closely. I was fooling around with it in an attempt to use RF=2, but that code has been dead for awhile and I can't say I know what state it's in.

It's not quite clear to me what you are proposing. Do you want to ignore unhealthy ingesters on query? or do you want to only query the relevant ingesters using the hash of the trace id?

Either change would need to be configurable so that default behavior remains the same.

**Comment by bikashmishra100** [comment]
I did not mean to touch `EventuallyConsistentStrategy `. I needed to make the strategy configurable and the default will always be the default strategy what is present. May be my words were not so clear.

There are two errors we see.
**During Ingestion**: When the ingester is unhealthy during the restarts, there is quite a lot of trace rejections. We thought if the traces are routed to the next ingester based on hash, the compactor may fix it in next cycle if few of the traces land up in other ingester.

**During Query**: Since the query requires all the ingesters to be healthy, we want to restrict only to the relevant ingesters to avoid loading the ingesters and also make the query more reliable.

**Comment by joe-elliott** [comment]
Ah, you are looking to productionize RF1. This is a bit more aggressive then just querying a subset of ingesters based on TraceID. I thought about what this would take a few months back but haven't done anything with it. Both of your suggested changes are worth doing.

I fully support adding these capabilities to Tempo, but we should break this into two separate PRs: one for the write and one for the read path. I see those as independent changes and it will simplify the reviews. If you have questions about how to go about making these changes please let me know! I'm not an expert in the ring but I've dug into it a few times and can probably give pointers.

**Comment by bikashmishra100** [comment]
Yes, fully agree that we will make separate PRs.

I am wondering how replication strategy would help. When RF=1, the Get method of ring will return a single instance. After that all the strategy can do is whether to use the instance or drop it. There is no other way to advance to next instance on the ring. I am rethinking whether dabbling with strategy would really help. 

https://github.com/grafana/tempo/blob/v1.4.1/vendor/github.com/grafana/dskit/ring/ring.go#L401

**Comment by mdisibio** [comment]
Want to mention that Tempo originally had this behavior, of querying only the target ingesters based on the trace ID.  It ended up being too brittle because as the ring topology changes the trace won't hash to the same ingesters, and can't be found again until it reaches the backend.  Querying all ingesters was introduced in https://github.com/grafana/tempo/pull/557

Sounds fine since the plan is to make it configurable.

**Comment by joe-elliott** [comment]
> I am wondering how replication strategy would help. When RF=1, the Get method of ring will return a single instance. After that all the strategy can do is whether to use the instance or drop it. There is no other way to advance to next instance on the ring. I am rethinking whether dabbling with strategy would really help.

My thought was to make a new Operation called `WriteWithSpillover` that implements the `ShouldExtendReplicaSetOnState` called here:
https://github.com/grafana/tempo/blob/v1.4.1/vendor/github.com/grafana/dskit/ring/ring.go#L390

This operation would extend replication set when it sees an unhealthy ingester.
