### ISSUE TITLE
Tempo cluster sizing  / capacity planning

### ISSUE THREAD

**Issue by pavolloffay** [grafana/tempo#1540]
**Is your feature request related to a problem? Please describe.**

I would like to know (approximately) Tempo cluster size and how many resources it will need for a given ingestion rate and retention - number of spans/time, average byte span size, retention N days (maybe I am missing some input parameters).

Such a document is useful when evaluating tempo from the cost perspective or capacity planning.

**Describe the solution you'd like**

Documentation on Tempo cluster sizing.

**Describe alternatives you've considered**

Run tests Tempo

**Additional context**

**Comment by pavolloffay** [comment]
Could you please describe what queries the test was doing? Is the lookback or time range affecting query resources? Was query part using functions or just scaled querier?

**Comment by pavolloffay** [comment]
Does retention anyhow affect resource requirements?

**Comment by mdisibio** [comment]
> Could you please describe what queries the test was doing? Is the lookback or time range affecting query resources? Was query part using functions or just scaled querier?

This was gathered from our own clusters which run real workloads and have a mixture of trace lookups and searches, and lookback of 1 or 24H, and using both querier pods and functions.  Total querier resources is a function of data volume involved in a search.  All queries are sharded into fixed-size sub-jobs, so a 2x time range will scan 2x data, and likewise a cluster with 2x volume across same time range.  Scaling up pods or functions can keep latency down by executing more sub-jobs in parallel.

> Does retention anyhow affect resource requirements?

Retention affects how many blocks exist, which mostly impacts latency and object store requests. Tempo reads a bloom filter per block, so 2x retention will issue 2x reads to object store.  Latency can be controlled by scaling up queriers to check more bloom filters in parallel (and more recently making use of https://github.com/grafana/tempo/pull/1388). Increased block list also has a small but not significant increase in memory since block metadata including name/size/location is kept in memory.

**Comment by pavolloffay** [comment]
@mdisibio could re-open this ticket and perhaps document the resources in the docs? 

We have used values in this ticker in the Tempo Kubernetes operator and we would like to keep them updated if storage or other components change.

**Comment by mdisibio** [comment]
Got it, reopening.  Expecting the requires to change in Tempo 2.0 with TraceQL and full parquet, will gather new numbers then.

**Comment by joe-elliott** [comment]
This will not block Tempo 2.0 from releasing so I'm moving it out of the v2.0 milestone.

**Comment by joe-elliott** [comment]
Heads up to @electron0zero and @mapno that this issue exists. After you do your research please publish some guidelines for the community and close out this issue.

**Comment by knylander-grafana** [comment]
I'm happy to add this information to the documentation when it's ready.

**Comment by knylander-grafana** [comment]
See also https://github.com/grafana/tempo/discussions/2836

**Comment by Jaland** [comment]
I have someone installing the operator on Openshift and we kept noticing an OOM error on our `tempo-tracing-stack-query-front` pod, but we were getting confused cause it was only using about half the memory requestion for the pod before hitting the CrashBackLoop.

After a little investigation, we noticed that the pod consists of two containers (`tempo` and `tempo-query`). It seems like the `tempo-query` container is doing 90% of the work and sucking up all the memory but for some reason the memory usage is split evenly between the pods so we OOM after only using half the memory as mentioned above. 

It would probably be a better use of resources if `tempo` was just hard coded with a relatively low amount since it does not seem to be using much and maybe given like 2% cut of the rest of the memory.

**Comment by venkatb-zelar** [comment]
@mdisibio may i know how you calculated the ingestion rate of 1MB/sec?

**Comment by lukasmrtvy** [comment]
@mdisibio for which component ? 🤷

**Comment by knylander-grafana** [comment]
We now have a basic doc that provides an example cluster sizing and mentions sizing considerations. This doc is meant to be a starting point. We can iterate on it as we need to: https://grafana.com/docs/tempo/latest/setup/size/

**Comment by mdisibio** [comment]
Closing because the new sizing page seems sufficient for now. It's hard to get more detailed because tracing workloads widely differ.  We can reopen this later if needed.
