### ISSUE TITLE
Parquet Storage Panic

### ISSUE THREAD

**Issue by altanozlu** [grafana/tempo#1541]
**Describe the bug**
We have been using parquet for a week but suddenly it's crashed and whenever i try open it it's crashed again. I've removed tempo data folder to make it work. The disk was not full.

**Environment:**
 - Infrastructure: Ubuntu 22
 - Deployment tool: Compiling branch main(08a4995030c72869fea9a4b67928ad0b2eff8675) to binary.

**Additional Context**
`"failed to pushToQueue traces to tenant single-tenant queue: queue is full"

panic: runtime error: index out of range [0] with length 0

goroutine 368 [running]:
github.com/grafana/tempo/tempodb/encoding/vparquet.traceToParquet(0xc066004480?)
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/schema.go:171 +0x1a2c
github.com/grafana/tempo/tempodb/encoding/vparquet.CreateBlock({0x2493e38, 0xc0000500b0}, 0xc000a34690, 0xc00cbedb88?, {0x2486670, 0xc0c4ff7140}, {0x2494420, 0x3524180}, {0x249ffc0, 0xc000d08160}, ...)
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/create.go:58 +0x1f2
github.com/grafana/tempo/tempodb/encoding/vparquet.Encoding.CreateBlock(...)
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/encoding.go:32
github.com/grafana/tempo/tempodb.(*readerWriter).CompleteBlockWithBackend(0xc000357140, {0x2493e38, 0xc0000500b0}, 0xc031d908c0, {0x2483220, 0x3524830}, {0x249ffc0, 0xc000d08160}, {0x249bfe0, 0xc000d08170})
        /root/tempo/repo/tempo/tempodb/tempodb.go:240 +0x396
github.com/grafana/tempo/modules/ingester.(*instance).CompleteBlock(0xc00037b560, {0x12, 0x2f, 0xa3, 0x13, 0xa0, 0xb1, 0x45, 0xbf, 0xb7, ...})
        /root/tempo/repo/tempo/modules/ingester/instance.go:294 +0x163
github.com/grafana/tempo/modules/ingester.(*Ingester).handleComplete(0xc000b38f00, 0xc0a27bc7d0)
        /root/tempo/repo/tempo/modules/ingester/flush.go:250 +0x25f
github.com/grafana/tempo/modules/ingester.(*Ingester).flushLoop(0xc000b38f00, 0x7)
        /root/tempo/repo/tempo/modules/ingester/flush.go:203 +0xc7
created by github.com/grafana/tempo/modules/ingester.New
        /root/tempo/repo/tempo/modules/ingester/ingester.go:89 +0x1f0`

**Comment by mdisibio** [comment]
Hi, thanks for reporting this.  The error is occurring when Tempo extracts the trace ID [from the first span](https://github.com/grafana/tempo/blob/08a4995030c72869fea9a4b67928ad0b2eff8675/tempodb/encoding/vparquet/schema.go#L171).  In this case there must not be a first span, and therefore `tr.Batches[0].InstrumentationLibrarySpans[0].Spans[0].TraceId` gives the `index out of range` error.  We can definitely change this line of code to safely detect this condition, however I don't think it's possible to emit real traffic like this in any protocol, so I suspect a different root cause like a corrupt WAL.   I see the other error pasted `failed to pushToQueue`, however this is related to metrics-generator and should not cause an issue with the WAL.  Were there any other errors too?
