### ISSUE TITLE
Tempo dashboard not showing metrics

### ISSUE THREAD

**Issue by irizzant** [grafana/tempo#1911]
**Describe the bug**
I have Tempo deployed in microservices mode from tanka in my kubernetes cluster.

I used the dashboards available here:
https://github.com/grafana/tempo/tree/main/operations/tempo-mixin

and imported them in my Grafana, they show empty.

I noticed that the `cluster` variable is not populated (empty), because the dashboard itself pulls it like this (see [here](https://github.com/grafana/tempo/blob/b35a0a6d3d8db0fac30f5d988bde0376b1ea937d/operations/tempo-mixin/dashboards/dashboard-utils.libsonnet#L27)):
`label_values(tempo_build_info, cluster)`

but `tempo_build_info` does NOT contain any cluster label.

I know one can override:
```
cluster_selectors: [$._config.per_cluster_label, 'namespace'],
    job_selectors: [$._config.per_cluster_label, 'namespace', 'job'],
    tenant_selectors: [$._config.per_cluster_label, 'namespace', 'tenant'],

```
and exclude the `cluster` label from the selectors, but I still think that exporting `cluster` as default label could be an improvement.

**To Reproduce**
1. Start Tempo (c7b854ef) in microservice mode with Tanka
2. Add the [dashboards](https://github.com/grafana/tempo/tree/main/operations/tempo-mixin) 
3. Verify that the `cluster` label is empty

**Expected behavior**
Tempo metrics should report the cluster label

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Additional Context**

**Comment by kvrhdn** [comment]
Tempo itself can not reliably report the `cluster` label since it's not aware of the infrastructure it is running in. Instead the `cluster` label should be populated by the Prometheus instance scraping Tempo. You can configure your scrape configs to include labels like `cluster`, `namespace` and `pod`.

**Comment by irizzant** [comment]
I thought the `cluster` label was about Tempo internals.

Nevertheless I have Loki installed and it uses the same `cluster` label, the difference is that Loki dashboards use regexp for that `cluster=~.`
This way even if metrics don't report the `cluster` label the dashboards can show data.

**Comment by kvrhdn** [comment]
I see, in the tempo-mixin we use [`addMultiTemplate `](https://github.com/grafana/tempo/blob/b35a0a6d3d8db0fac30f5d988bde0376b1ea937d/operations/tempo-mixin/vendor/github.com/grafana/jsonnet-libs/grafana-builder/grafana.libsonnet#L44) to create the dropdown variable. This uses `.+` by default instead of `.*`.

**Comment by irizzant** [comment]
Thanks for the PR, but what about the Tempo Operational dashboard? It doesn't appear among the changed dashboards at all
