### ISSUE TITLE
Fix distributor http status codes

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#1958]
**Describe the bug**
As reported by the community if the ingester returns trace too large then the returned http error is 500. This error suggests to the otel collector to retry however it should return 400 which suggests to not retry. Currently the GRPC status codes correctly suggest retrying or not.

Review the status codes for various errors and return 400s where appropriate.

**Comment by joe-elliott** [comment]
@mghildiy is going to take a crack at this.

cc @ie-pham b/c you're also looking at return codes (but for proto/grpc)

**Comment by mghildiy** [comment]
So currently error code returned is 'FailedPrecondition

https://github.com/grafana/tempo/blob/c0127c78c368319433c7c67ca8967adbfed2259e/modules/ingester/instance.go#L189

https://github.com/grafana/tempo/blob/c0127c78c368319433c7c67ca8967adbfed2259e/modules/ingester/instance.go#L198

...defined here:

https://github.com/grafana/tempo/blob/c0127c78c368319433c7c67ca8967adbfed2259e/vendor/google.golang.org/grpc/codes/codes.go#L121

A better option can be:
https://github.com/grafana/tempo/blob/c0127c78c368319433c7c67ca8967adbfed2259e/vendor/google.golang.org/grpc/codes/codes.go#L57

Surprisingly, [grpC codes to http codes mapping](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/refs/tags/v1.21.4-pre1/doc/statuscodes.md) says that both map to 400.

**Comment by ie-pham** [comment]
Hi @mghildiy ,

Thank you so much for your contribution to this issue. Unfortunately, this issue is no longer is no longer relevant due to our shift towards a "partial success" solution, as outlined in #2571. In addition, [Otel](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#partial-success-1) states that partial successes should return a 200 instead of an error. 

Your contribution to this repo is well observed by the team and is highly valued. Don't be deterred to explore other opportunities to contribute!  

Closing this issue.
