### ISSUE TITLE
[Grafana Cloud Traces] Traces search returns missing trace name and wrong duration

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/tempo#2057]
**Describe the bug**

Grafana Cloud Traces search return some traces with missing span name ("<root span not yet received>" or "") and wrong very short trace duration. 
In the search result screen, some traces are erraneous, some other are not, the errors change when we re execute the query.

See screenshot
![image](https://user-images.githubusercontent.com/459691/216352034-4ae8de88-43bc-490a-bd28-50a20cdec9ae.png)

**To Reproduce**

This problem can be reproduced instrumenting a SpringBoot App with Otel Java Auto Instr 1.21 send OTLP signals to Grafana Agent 0.31 sending signals to Grafana Cloud Traces, Logs, and Metrics (example [here](https://github.com/cyrille-leclerc/my-shopping-cart/tree/grafana)).

Another way to reproduce is the following
* Get a Grafana Cloud account
* Install Jenkins and the [Jenkins OpenTelemetry Plugin](https://plugins.jenkins.io/opentelemetry/) and a Grafana Agent 0.31 
* Configure 
   * Grafana Agent to sendd OTLP to Grafana Cloud Traces, Logs, and Metrics (ie Tempo, Loki, and Mimir) 
   * Jenkins to send OTLP signals to the Grafana Agent
   * Also send the traces to Jaeger for verification
* Create and run a Jenkins Pipeline similar to https://github.com/cyrille-leclerc/ecommerce-antifraud
* Verify in Grafana Cloud Explore the produced traces (eg search and `service.name=jenkins` and attribute `type="job"`

**Expected behavior**

Span name and duration are properly reported in the "search results view" and match the data reporter in the trace gantt viz screen

**Environment:**
 - Infrastructure: Grafana Cloud
 - Jenkins OpenTelemetry Plugin 2.10.1-SNAPSHOT (Otel Java SDK 1.19.0) or a plain Otel Java Instrumentation 1.21.0 with a Spring Boot application.

**Additional Context**

**Comment by cyrille-leclerc** [comment]
The problem looks different from the following previously reported problem because of the invalid duration that impacts #2057 but is not reported in #1476
* https://github.com/grafana/tempo/issues/1476

**Comment by joe-elliott** [comment]
Thanks for the report! What you are discussing is a difficult problem to solve although we can certainly improve the situation. The fundamental issue is that a search may match one of many parts of a trace. The part that was matched may then be missing key information such as the root span or the full trace duration. Then, when you do a trace by id search, we return the entire trace because we merge all of these parts together.

Why are there parts:

**Replication Factor**
When running Tempo with RF=3 we store 3 copies of the trace for durability and availability. This is the mode we run in GCT. Due to the nature of quorum writes it is not guaranteed that all three of these traces are exactly the same although most of the time they are. 

**Recent Traces**
Tempo makes a choice after a configurable number of seconds to flush a live trace to the wal as a partial trace. It can never be sure that a trace is complete so it may, shortly after flushing, receive more spans for that trace. As long as those parts exist in the wal they can cause some of the inconsistencies you are showing. Once the wal block is cut to a complete block these partial traces are recombined into one. In GCT we flush a trace after 20 idle seconds and we cut the wal into a complete block every 15 mins.

Now we have made [recent improvements](https://github.com/grafana/tempo/pull/2003) that have been deployed to GCT since you filed this issue. Can you check again and see if anything has improved?

Finally, all of this is not to say that there are no bugs in here Tempo. There very well may be, but isolating them can be difficult due to the issues discussed above.

**Comment by cyrille-leclerc** [comment]
Thank you very much Joe.

> The fundamental issue is that a search may match one of many parts of a trace. 

> Due to the nature of quorum writes it is not guaranteed that all three of these traces are exactly the same although most of the time they are.

Please note that the search criteria used in this problem (span name) exclusively matches with the root span and none of the child span. 

Moreover, the problem also happens on traces that have been persisted in GCT more than 5 mins before the query in the screenshot so I would expect the data to be persisted in all stores. I can reproduce the problem with traces that are several days old.

Does this help qualify the problem?
