### ISSUE TITLE
Span sets returned by TraceQL should return the number of all matching spans

### ISSUE THREAD

**Issue by stoewer** [grafana/tempo#2307]
**Is your feature request related to a problem? Please describe.**

When the Search API finds traces via TraceQL queries, each returned `spanSet` contains the matching spans within each trace. The maximum number spans in the `spanSet` is currently limited by [spansPerSpanSet](https://github.com/grafana/tempo/blob/97daaacebb58e6e0005f1c380894082dd1081753/pkg/traceql/engine.go#L22). Therefore, the number of returned spans in the `spanSet` can be lower than the actual number of matches. The `spanSet` contains a field [`matched`](https://grafana.com/docs/tempo/latest/api_docs/#example-of-traceql-search) but this field is always set to the [number of returned spans](https://github.com/grafana/tempo/blob/97daaacebb58e6e0005f1c380894082dd1081753/pkg/traceql/engine.go#L134).

As a consequence it is not possible to know whether the returned spans are all spans that matched the query.

**Describe the solution you'd like**

The field `matched` in `spanSet` should contain the number of all spans that matched by the query.

**Additional context**

This feature also allows the UI to implement visual aides that indicate whether a span set contains all matched spans or not.

**Comment by mghildiy** [comment]
I would like to take this one.

**Comment by joe-elliott** [comment]
Sure. The spansets are passed into the query engine here:

https://github.com/grafana/tempo/blob/4cdf859fc1583cac4ebf6ba70afc668764813cce/pkg/traceql/engine.go#L47

Any spansets that have "passing spans" are trimmed down here. Really this should be configurable but is currently hardcoded to 3:

https://github.com/grafana/tempo/blob/4cdf859fc1583cac4ebf6ba70afc668764813cce/pkg/traceql/engine.go#L60

After the lines above the spansets go back into the fetch layer (with a max of 3 spans each) and are decorated with metadata such as span id, trace id, etc. Then they come out here and are translated into the object that is eventually unmarshalled to json and returned by the api:

https://github.com/grafana/tempo/blob/4cdf859fc1583cac4ebf6ba70afc668764813cce/pkg/traceql/engine.go#L88

To make this fix we will need to add a new field to the [spanset](https://github.com/grafana/tempo/blob/main/pkg/traceql/storage.go#L59) indicating the total number of matching spans (before we reduce to 3). Then when the spanset is translated into the API object we can use this new value instead of the [length of spans](https://github.com/grafana/tempo/blob/4cdf859fc1583cac4ebf6ba70afc668764813cce/pkg/traceql/engine.go#L140).

**Comment by mghildiy** [comment]
I am picking up golang, so please bear with me if my changes are a bit delayed.

**Comment by joe-elliott** [comment]
> I am picking up golang, so please bear with me if my changes are a bit delayed.

No excuses necessary. We appreciate you taking on the work :pray:

**Comment by mghildiy** [comment]
I debugged the test, found that at 

https://github.com/grafana/tempo/blob/4cdf859fc1583cac4ebf6ba70afc668764813cce/pkg/traceql/engine.go#L68

returned response  dont contain the matched span value set earlier by me...seems in Fetch those values are stripped. Need to investigate more.

**Comment by joe-elliott** [comment]
ok, yeah. in the fetch layer we drop the spanset and pass all spans back through some metadata iterators:

https://github.com/grafana/tempo/blob/089772bba3c50293ef3ac3fa615e7e1ff8a9ad73/tempodb/encoding/vparquet2/block_traceql.go#L292

this is going to be tough. it will require rethinking the way decorate matched spans with metadata. this is going to come up anyway when we do grouping so we will have to solve it then.

**Comment by mghildiy** [comment]
Got it, and mock span iterator in engine_test replicates same behaviour, hence test also behaves same.

**Comment by mghildiy** [comment]
So I stop working on this issue?

**Comment by joe-elliott** [comment]
> So I stop working on this issue?

I think this is a quite a difficult issue that requires some very thoughtful changes to the fetch layer that also take into account future changes related to `select` and `group` functionality. So, yeah, that's a pretty huge ask for someone new to the codebase. We do very much appreciate you taking a look!

**Comment by stoewer** [comment]
> If you are interested in contributing otherwise I would consider looking for things tagged "good first issue"

I'm removing the "good first issue" label from this issue as it turned out to be misleading
