### ISSUE TITLE
Cannot use `otel.library.name` in TraceQL

### ISSUE THREAD

**Issue by nabadger** [grafana/tempo#2352]
Hi, 

I would like to know if this is possible or not? 

Currently I cannot seem to query "otel.library.name" or "otel.library.version", although I can see them as attributes in the trace.

I've tried following https://grafana.com/docs/tempo/latest/traceql/#selecting-spans and I've seen reference that these are intrinsic fields, but other fields of the same type do seem to work.

Thanks

**Comment by nabadger** [comment]
In my example, these appear to be under `scopeSpans` for me.

```json
{
  "scopeSpans": [
    {
      "scope": {
        "name": "opentelemetry.instrumentation.django",
        "version": "0.38b0"
      },
      "spans": [
        { ...
        }
      ]
    }
  ]
}
```

In Grafana, under _Resource _Attributes__ I have:
- `otel.library.name` =  `opentelemetry.instrumentation.django`
- `otel.library.version` =  `0.38b0`

**Comment by joe-elliott** [comment]
This is due to Grafana rendering these attributes incorrectly. We are asking for them to be fixed here:

https://github.com/grafana/grafana/issues/59607

However, even if Grafana renders these correctly, they are still not referenceable in TraceQL. Currently there is no way to reference any values at the "scope" level.

**Comment by nabadger** [comment]
Thanks both for the replies :)

**Comment by joe-elliott** [comment]
Closing in favor of #2189
