### ISSUE TITLE
max_outstanding_per_tenant config worng

### ISSUE THREAD

**Issue by lovesharepc** [grafana/tempo#2444]
**Describe the bug**
follow doc
https://grafana.com/docs/tempo/latest/configuration/#:~:text=max_outstanding_per_tenant
```
query_frontend:
  search:
    max_outstanding_per_tenant: 10000
```

will get error
```
failed parsing config: failed to parse configFile /etc/tempo.yaml: yaml: unmarshal errors:
line 100: field max_outstanding_per_tenant not found in type frontend.SearchConfig
```

use api check 
real config is 
```
query_frontend:
  max_outstanding_per_tenant: 10000
  search:
    
```

**To Reproduce**

**Expected behavior**

**Environment:**
 - Infrastructure: [docker]
 - Deployment tool: [docker]

**Additional Context**
```
tempo, version 2.1.1 (branch: HEAD, revision: 4157d7620)
  build user:       
  build date:       
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             unknown
```

**Comment by joe-elliott** [comment]
cc @knylander-grafana

**Comment by knylander-grafana** [comment]
Thank you for reporting this! 

I searched through the doc and max_outstanding_per_tenant is listed in three files: 
* configuration/_index.md (page you highlighted) - Fixed in latest release.
* backend_search.md - Indent is correct
* manifest.md (auto-generated) - Indent is correct

I don't think we need any additional changes.
