### ISSUE TITLE
Tempo Search not returning results for non-String (Boolean and Long) Tags #70062

### ISSUE THREAD

**Issue by Chelsea-Barraball** [grafana/tempo#2556]
**The Bug**

When searching for non-String tags in Tempo using the `Search` tab, I get 0 series returned:

<img width="560" alt="Screenshot 2023-06-13 at 10 50 25" src="https://github.com/grafana/tempo/assets/121564401/65471de2-fa96-45a6-b533-fcc6890054be">

However, when using TraceQL and searching on {.net.peer.port=5432}, I get the expected traces.

This problem occurs only with boolean and long tags.

An added note: I've noticed that Tempo returns and recommends String values for these tags, for example autocomplete gives net.peer.port="5432" instead of net.peer.port=5432. Oddly enough, searching for http.status_code="200" works fine in the `Search` tab.

When I curl `/api/search/tag/<tag>/values` for each of these tags, I get their values successfully, but `/api/search?tags=...` returns nothing.

I'd love some advice or help with this issue!

**To Reproduce**
Step 1: Open Grafana and go to Explore, go to the Search tab.
Step 2: Search for a non-String tag, such as `net.peer.port=5432`
Step 3: The Search should return `0 series returned`

**Expected behavior**
I expect the same series to be returned as when I use TraceQL, but for some reason long/boolean tags are not returning any series when using the `Search` tab.

**Environment:**
 - Infrastructure: Kubernetes
 - Grafana version: `9.5.2`
 - Tempo version: `2.1.1`

**Comment by mdisibio** [comment]
Sorry but yes the old tag-based search only looks at string values, except for `http.status_code` and a few other special-case attributes.  To be honest I don't think we'll fix this as we are moving everything over to traceql, including the frontend in your screenshot (it will become a traceql query builder similar to mimir and loki).   Since traceql works as expected, is there a reason it doesn't work for your use case?
