### ISSUE TITLE
Review/Fix Query Frontend cancellation behavior

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#2680]
While reviewing frontend cancellation I noticed some possibly inconsistent behavior. This issue will document what was found as well as what needs to be researched and improved.

**Observed Behavior**

1. When executing a query that exceeded the Tempo timeout (`2m` in this case) Grafana frontend receives a 504 and shows the following error:

![image](https://github.com/grafana/tempo/assets/2272392/10b61945-f428-4f95-8431-4c6452460d64)

Tempo logs a partially complete job with a 200:

![image](https://github.com/grafana/tempo/assets/2272392/3e165c69-0c7d-4371-8714-4f0351a931dc)

2. If you start a query and instantly click the "Cancel" button in Grafana the query will still complete in Tempo.

![image](https://github.com/grafana/tempo/assets/2272392/e4b54f95-d915-4119-a983-645298ffd2c7)

**To Do:**

1. Review behavior of the query frontend in the face of different cancellation events
1. Establish appropriate behavior and make any adjustments as necessary
1. Consider this behavior both in terms of the HTTP and streaming GRPC query endpoints

**Cancellation Events:**

1. Execute a request that exceeds the timeout
1. Execute and then cancel a request before it has timed out

It would be interesting to do these in the context of Grafana specifically since it is the most common Tempo client.

**Comment by zalegrala** [comment]
I've had a chance to review a bit of the situation.

The 504 condition seen in the browser is coming from the Grafana data source timeout.  The timeout is configurable and for the environment above, is set to the 2 minutes seen in the browser inspection.  I think we can mostly ignore this unless we want the tempo timeouts to be slightly less than the 2 minutes so that tempo returns a timeout response of some sort.

I see [one place in code](https://github.com/grafana/tempo/blob/main/modules/frontend/searchsharding.go#L164) that we don't clean up the in flight requests upon cancellation.  I believe we should cancel the requests at this place also to avoid doing work that is no longer being requested.

The two conditions mentioned that need a little adjustment.  Here is what I'm thinking:
* A timeout on the tempo side should result in an http 408 status with a body of `context deadline exceeded`, which is the context error when a timeout is reached.
* A cancellation on the client side closes the TCP connection to the server, resulting in a `context canceled` message.  In this case, we have no caller to return a body to, and so I believe the logging is the only concern.  I think 499 is the best status code here, but is not included in the standard lib due to not being included in the IANA spec.  However, we can likely just write `499` directly instead of using the `http` constants if we agree that this is an acceptable way to proceed.  https://en.wikipedia.org/wiki/List_of_HTTP_status_codes for reference, note the 499 under unofficial codes.

**Comment by joe-elliott** [comment]
> I see [one place in code](https://github.com/grafana/tempo/blob/main/modules/frontend/searchsharding.go#L164) that we don't clean up the in flight requests upon cancellation. I believe we should cancel the requests at this place also to avoid doing work that is no longer being requested.

We should patch this up and do some testing to make sure this properly cancels in flight jobs.

> A timeout on the tempo side should result in an HTTP 408 status with a body of context deadline exceeded, which is the context error when a timeout is reached.
 
This is tougher b/c there are a lot of timeouts in tempo. My guess is right now it would return a 500? The two I'm thinking about are the querier search timeout for one job. If this times out I believe the retry middleware will retry the job a configurable number of times.

The second timeout is at the query frontend configured in the dskit server. Honestly not sure what happens if this times out. 

I guess 408 is appropriate? It does seem weird to call this a client error.

> A cancellation on the client side closes the TCP connection to the server, resulting in a context canceled message. In this case, we have no caller to return a body to, and so I believe the logging is the only concern. ...

I've seen 499 used before in nginx to indicate the same and i think this would be a good addition to tempo for clarity.

**Comment by zalegrala** [comment]
Between the two merged PRs, I think we got what we came for.  Feel free to re-open if I've overlooked something.
