### ISSUE TITLE
Inconsistent option naming for instance_interface_names

### ISSUE THREAD

**Issue by stevensdavid** [grafana/tempo#2716]
**Is your feature request related to a problem? Please describe.**

As shown in the [manifest of configuration options](https://grafana.com/docs/tempo/latest/configuration/manifest/), the option for changing interface names in a ring is called `instance_interface_names` for the `compactor`, `distributor`, and `metrics_generator`. However, for the `ingester` it is called `interface_names`. 

Furthermore, the nesting seems a bit different. For the `ingester` the option is found at `ingester.lifecycler.interface_names`, thus making it a sibling to the `ring` option, while for the others it is found at `ring.instance_interface_names`.

**Describe the solution you'd like**

This is confusing, as I would expect consistency here. The easiest thing would probably be to move `ingester.lifecycler.interface_names` to `ingester.lifecycler.ring.instance_interface_names`, but I understand that this would be a breaking change as old configurations using the option would no longer be valid. Maybe a configuration alias could be added so both paths are supported, with one of them taking precedence over the other?

**Describe alternatives you've considered**

It's possible that this is due to some underlying library or other reasons that I don't know enough about the Tempo architecture to be aware of - I apologize if so!

**Additional context**

**Comment by joe-elliott** [comment]
So this is all inherited from Loki I believe. The difference is that the ingester exposes the lifecycler config directly:

https://github.com/grafana/tempo/blob/2cb5a7bb03729b6ae51ea56bd2b2e54dd5ef91cb/modules/ingester/config.go#L19

The other components expose a subset of the config and then have a `ToLifecylerConfig()` method to generate the real config:

https://github.com/grafana/tempo/blob/2cb5a7bb03729b6ae51ea56bd2b2e54dd5ef91cb/modules/distributor/config.go#L31
https://github.com/grafana/tempo/blob/2cb5a7bb03729b6ae51ea56bd2b2e54dd5ef91cb/modules/compactor/config.go#L18C18-L18C28

I imagine this was done with the idea of simplifying the config for the non-ingester components. Off the cuff I think the fix is just to expose the full lifecycler config on all components for consistency. WDYT?

We could probably do something where we support both configs for a release or two then drop the old ones.

**Comment by stevensdavid** [comment]
I think the most important thing for me as a user is consistency here, so exposing the full lifecycler config on all components sounds reasonable 👍
