### ISSUE TITLE
Tempo Explore: Wrong duration of the traces

### ISSUE THREAD

**Issue by nkondratyk** [grafana/tempo#2734]
**Describe the bug**
We noticed that for some of the traces (mostly which have async calls) the duration of the specific trace in the table view is different when you open the view with spans for that trace

As you can see on the screen in the duration column with the list of traces the duration is 42ms but when we open it, the duration is 12.37s (which is correct)
![image](https://github.com/grafana/tempo/assets/34338539/e85c811c-d06c-4e8d-81f0-b56fcf9134e3)

After around 20 minutes, it starts showing the correct duration.
![image](https://github.com/grafana/tempo/assets/34338539/cb41ff3d-34b0-4182-9348-d568332efec5)

**To Reproduce**
1. Go to Tempo Explore
2. Go to Search and specify Service name and Span Name
3. Click on the Trace and see the difference in the duration

**Expected behavior**
The right duration of the trace (in the table with the list of traces) will be displayed immediately and not after ~20 minutes.

**Environment:**
Grafana in Kubernetes: v10.0.1
Browser: Google Chrome Version 114.0.5735.198
Tempo version: 2.1.1

**Additional Context**

**Comment by joe-elliott** [comment]
As Tempo receives traces it uses a cutoff to determine when to write it to a block:

```
ingester:
  trace_idle_period: 10s
```

It sounds like this idle period is getting hit and your trace is getting fragment as it's written to the blocks. When you do your search you are finding one of these fragments which is why the duration is incorrect. If multiple fragments are found we do attempt to combine them in a sensible way here:

https://github.com/grafana/tempo/blob/main/pkg/traceql/combine.go#L49

However, if your search doesn't match all fragments or if the limit of 20 is hit before all fragments are found you will get situations like you are detailing in this issue.

Over time, as your blocks are compacted and combined, the trace fragments are merged into one which is why you are seeing it all eventually come to the correct value.

There is no "fix" for this issue. If you increase the idle period mentioned above you can minimize it, but be warned your ingesters will use more memory.
