### ISSUE TITLE
Tempo support Azure Stack blob storage as backend 

### ISSUE THREAD

**Issue by oyzl1230** [grafana/tempo#2774]
We are try to deploy the Tempo in our Azure Stack environment, follow the guild line to use Azure blob as the backend storage, provided the parameters as below:
storage:
      trace:
        backend: azure
        azure:
          container_name: tempo
          storage_account_name: obs
          storage_account_key: ${AZURE_STORAGE_KEY}
          endpoint_suffix: blob.loacation01.example.demo.com
however, we get the error message "failed to init module services error initialising module: store: failed to create store failed to GetProperties: Get \"http://blob.loacation01.example.demo.com/obs/tempo?restype=container&timeout=61\": dial tcp: lookup blob.loacation01.example.demo.com on 192.168.0.10:53: no such host".
to access Azure / Azure Stack blob, the url should be as "https://storage_account_name.endpoint_suffix/container_name/blob". the different for Azure and Azure Stack is, the endpoint_suffix of public Azure is blob.core.****, and Azure Stack is blob.***. in our case, the url should be like “http://obs.blob.loacation01.example.demo.com/tempo/blob" instead of "http://blob.loacation01.example.demo.com/obs/tempo". 
could you help to fix this issue. thanks

**Comment by chlislb** [comment]
Hi, joe-elliott,
Yes, this occur within Azure client. 
Azure Stack Hub is [Azure on premise solution](https://learn.microsoft.com/en-us/azure-stack/user/user-overview?view=azs-2301). 
The blob endpoint is different between different deployment, but they all have the same prefix "blob."
example endpoint in "blob.local.azurestack.external" in [Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-storage-dev?view=azs-2301)

in [https://github.com/grafana/tempo/blob/main/tempodb/backend/azure/azure_helpers.go]
(https://github.com/grafana/tempo/blob/main/tempodb/backend/azure/azure_helpers.go#L106), 
the author want to support Emulator scenario, but is skip Azure Stack Hub scenario. So I would like to suggest use "blob." instead of "blob.core" as prefix to filter.
that says change from
`	if !strings.HasPrefix(cfg.Endpoint, "blob.core") {
		u, err = url.Parse(fmt.Sprintf("http://%s/%s", cfg.Endpoint, accountName))
	}`

to
`	if !strings.HasPrefix(cfg.Endpoint, "blob.") {
		u, err = url.Parse(fmt.Sprintf("http://%s/%s", cfg.Endpoint, accountName))
	}`
I have tested in our local, it works well on Azure Stack Hub.

By the way, as CONTRIBUTOR document say, if a trivail fix, create a pull request. I would like know if every one can create pull request and do you have pull request branch naming convention? It is better to have a reference how to do it. I am new on open source contributor.

**Comment by joe-elliott** [comment]
Ah, I see. Nice find!

Would you like to submit a PR to fix? If not I can.

**Comment by chlislb** [comment]
Thanks, let me try to submit a PR, I will sync the status

**Comment by chlislb** [comment]
please review https://github.com/grafana/tempo/pull/2853

**Comment by chlislb** [comment]
Thank you very much!
