### ISSUE TITLE
Issues running command 'tempo-cli query api search'

### ISSUE THREAD

**Issue by migruiz4** [grafana/tempo#2913]
**Describe the bug**
Command 'tempo-cli query api search' fails with the following error:

```console
$ ./tempo-cli query api search http://grafana-tempo-query-frontend
tempo-cli: error: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```

Although 'Start' and 'End' arguments are optional, I am able to workaround the first error by providing them, but then I will encounter a different error:
```console
$ tempo-cli query api search http://grafana-tempo-query-frontend:80 "" "2006-01-02T00:00:00Z" "2023-01-02T00:00:00Z"
tempo-cli: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: address http://grafana-tempo-query-frontend:80: too many colons in address"
```

The issue looks like an additional colon (`:`) is being added at the end of the Endpoint. 

**To Reproduce**
1. Download latest version of the `tempo-cli` binary
2. Run command `tempo-cli query api search`

**Expected behavior**
The start and end arguments should be optional.
The command should succeed.

**Environment:**
 - Infrastructure: Kubernetes/Laptop.
 - Deployment tool: Latest binary tarball for Linux AMD64 - https://github.com/grafana/tempo/releases/download/v2.2.2/tempo_2.2.2_linux_amd64.tar.gz

**Additional Context**

I have been able to reproduce the issue in MacOS and Debian 11, in both cases, the error is the same.

**Comment by joe-elliott** [comment]
> Although 'Start' and 'End' arguments are optional, I am able to workaround the first error by providing them, but then I will encounter a different error

These params are marked optional in the API and if you do not provide them then Tempo will fall back to it's old behavior of searching the ingesters only. This is unintuitive and I think we should just start requiring them at the API level. They are recently required in the CLI. See below.

> transport: Error while dialing: dial tcp: address http://grafana-tempo-query-frontend:80: too many colons in address

This error is occurring because I updated the CLI to use the GRPC streaming endpoint and GRPC doesn't accept a scheme. Try `grafana-tempo-query-frontend:9095`.

Both of these errors are occurring for the same reason. Recently I updated the CLI to use the GRPC streaming endpoint which requires a start/end time and has a different format for the endpoint. Honestly I probably should have created a new cli command and left this one to do the standard http search request.
