### ISSUE TITLE
Map database name in service graphs

### ISSUE THREAD

**Issue by josecoelho96** [grafana/tempo#3082]
Hi,

First of all, I'm not sure if this is right place to ask this. 

We're using the OpenTelemetry stack (java agent and collector) to collect metrics and traces from our application and sending them to Tempo.

It's a java application that connects with a single database running on the same host as the java app.
We have this arrangement in multiple hosts, where the database name is almost always the same and all of them are sending data to Tempo.
We were able to define the service name using the `otel.service.name` property of the java agent.

When I check the Service Graphs generated it appears as all the services are connecting to a single database, as it is almost always named the same.

Is it possible to change this behaviour and have each java app connected to one "database node"?

Thanks in advance

**Comment by joe-elliott** [comment]
I'm going to cc @mapno as he's most familiar with this functionality, but it seems to me that it's hardcoded to use `db.name`:

https://github.com/grafana/tempo/blob/f297c50b5a3c6ff98171a759649ee4364e74cdec/modules/generator/processor/servicegraphs/servicegraphs.go#L188C1-L188C1

We would definitely accept a PR to make this configurable.

**Comment by mapno** [comment]
That's right. Unfortunately it's not configurable.

**Comment by josecoelho96** [comment]
I would like to contribute by changing this behavior, if that's something worth doing. I never used Golang, so it would also be a nice thing to experiment on.

I was exploring the project for a bit and I couldn't find a doc explaining how to test changes locally. What I did was use the makefile, running the target `make docker-tempo` and using it within a docker-compose. I think it worked, but I'm not sure if that's the best way to do it.

What would a configuration to change this behaviour look like? My first iteration would be something like:
- a boolean to enable/disable this change
- an optional prefix
- an optional suffix
- a boolean to either include/exclude the app service name
Example:
- service called: `app1`
- database called `db`

Right now, the virtual node gets called `db`.
With this change, it could be `(prefix?)-(service-name?)-dbname-(suffix?)`

Does this make sense?

**Comment by joe-elliott** [comment]
> I was exploring the project for a bit and I couldn't find a doc explaining how to test changes locally. What I did was use the makefile, running the target make docker-tempo and using it within a docker-compose. I think it worked, but I'm not sure if that's the best way to do it.

This is a fine way to do it. I would recommend looking at the [distributed docker-compose](https://github.com/grafana/tempo/blob/main/example/docker-compose/distributed/docker-compose.yaml) in the repo. It includes the metrics generator sending metrics to a prometheus instance.

As far as the configuration goes I would just provide an optional string to use instead of 'db.name', but it seems like you are expecting people to want something more expressive. I think the best choice in that case would be to provide a regex to match which would give the user the flexibility to find all kinds of key names? Another option might be a list of names to all consider databases.

```
metrics_generator:
  processor:
    service_graphs:
      database_peer_attributes:
        - db.name
        - other.db.name
```

@mapno what is the relationship between the hardcoded "db.name" and the configurable "peer_attributes"? That might help inform how it should be configurable.

**Comment by mapno** [comment]
>@mapno what is the relationship between the hardcoded "db.name" and the configurable "peer_attributes"? That might help inform how it should be configurable.

`db.name` is a hard-coded form of virtual nodes for databases. It works somewhat similarly, but marks the node as `database`, instead of `virtual`.

The prefix-suffix approach looks interesting. What attributes could be used for that? Ideally, something from [database semantic conventions](https://opentelemetry.io/docs/specs/semconv/database/database-spans/#connection-level-attributes).

**Comment by josecoelho96** [comment]
Maybe I'm trying to overfit the proposed solution to my use case, but I think it would be helpful overall if the service name that called the database could be included in the virtual node.

@mapno is there a way to discuss this in more depth? This issue was closed as completed but I'm interested in discussing the approach to change this and even to try and implement it, if you are willing to discuss it. Let me know!

**Comment by mapno** [comment]
Ups, I didn't mean to close it, sorry 🤦 Clicked the wrong button.

Yes, let's discuss an approach. Contributions are very appreciated! We can keep the conversation here or switch to the [community slack](https://slack.grafana.com/), whatever you prefer.

>Maybe I'm trying to overfit the proposed solution to my use case, but I think it would be helpful overall if the service name that called the database could be included in the virtual node.

No, it's not a bad approach. What doesn't convince me is that two different services connecting to the same db would create two different db nodes. Ideally, we should uniquely identify the db node, rather than the `service-db` connection.

What uniquely identifies the db should ideally also come from [OTel semantic conventions](https://opentelemetry.io/docs/specs/semconv/database/database-spans/#connection-level-attributes), so it's useful to as many people as possible.

In any case, this feature should be configurable, so you should make it work with whatever approach works best for you—eg. `<app-name>.<db.name>`, like you were suggesting.

**Comment by zetaab** [comment]
<img width="530" alt="Screenshot 2023-11-11 at 16 06 12" src="https://github.com/grafana/tempo/assets/22482503/46b76888-ce7e-46f0-a841-8f46522126fb">

we have basically "almost similar" issue. 

The traces that are going to postgresql from kapi and dapi.

Traces using dapi:
db.name = dapi
db.system = postgresql

Traces using kapi:
db.name = kapi
db.system = postgresql

However, the main problem here is that these databases are two separate databases. Now the graph shows that these are exactly same system.
