### ISSUE TITLE
Add Markdown Spellchecker to CI

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#319]
**Is your feature request related to a problem? Please describe.**
I clearly am unable to spell #318.  Let's add a simple spell checker or linter to the CI to catch issues like this in markdown files and code comments.

**Describe the solution you'd like**
It appears that golangcilint has a "misspell" linter so perhaps we just need to adjust that configuration: https://golangci-lint.run/usage/linters/

**Comment by dgzlopes** [comment]
I researched this a bit. In theory, golangci `misspell` linter is working but only with code comments.

I tried [cspell](https://github.com/streetsidesoftware/cspell) and works well with Markdown files. The problem is that we've to maintain our own dictionary. Probably this ticket needs more research... Meanwhile, we have to double-check the syntax/grammar/spelling of the PRs.

**Comment by joe-elliott** [comment]
We are excellent spellers and do not live in fear of simple typos.  Let's go!
