### ISSUE TITLE
Connection refused - Tempo query frontend 9095 port

### ISSUE THREAD

**Issue by datsabk** [grafana/tempo#3204]
**Describe the bug**
I am facing a strange issue where I deployed `tempo-distributed` and I am facing issue of connection refused on port 9095 for Tempo query frontend. I am unable to figure out why this issue would happen - Is there some bind address that I could be missing? 

**To Reproduce**
1. No clue - Another similar setup on different account works 

**Expected behavior**
Query frontend should be able to accept the request

**Environment:**
Kubernetes-Helm

**Comment by joe-elliott** [comment]
This sounds like a pretty standard networking issue. I'd begin by exec'ing into the pod and attempting to connect to the port locally and then working my way out.

If you can't connect in the pod then this is likely a config issue. Otherwise this issue will be somewhere in the k8s deployment/service config.
