### ISSUE TITLE
OOM on TraceID Search

### ISSUE THREAD

**Issue by JustNZ** [grafana/tempo#3268]
**Describe the bug**
If I enter my TraceID in the Grafana Explore and start the search it's loading for a few seconds until `Query error: An error occurred within the plugin
` appears. 
In Tempo I can see the following log messages:

```
level=warn ts=2024-01-05T07:09:09.891747876Z caller=pool.go:222 msg="removing distributor_metrics_generator_pool failing healthcheck" addr=127.0.0.1:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
```
```
level=warn ts=2024-01-05T07:09:12.669595713Z caller=server.go:2136 traceID=68fa717f99af68c0 msg="GET /querier/api/traces/328c223b84d5b316?blockEnd=397829cbc14e5e0b0000000000000000&blockStart=343eb1a1f58d0fad0000000000000000&mode=blocks (500) 13.019705488s Response: \"error finding trace by id, blockID: 3533cc85-6a90-4ce8-828e-62e0b7bfa732: [] context done context deadline exceeded\\n\" ws: false; Accept: application/protobuf; Accept-Encoding: gzip; Connection: close; User-Agent: Grafana/x.x.x; X-Datasource-Uid: b122bba6-8d02-4c36-b9ef-fae2fa27e10a; X-Forwarded-For: x.x.x.x, x.x.x.x; X-Grafana-Org-Id: 1; X-Panel-Id: undefined; X-Real-Ip: x.x.x.x; X-Scope-Orgid: single-tenant; "
```

**To Reproduce**
1. Start Tempo (Version: 2.3.1)
2. Search for TraceID in Grafana Explore with TraceQL
3. Wait for red error message

**Expected behavior**
Get Trace

**Environment:**
 - Infrastructure: Installed on RHEL8 in a two server cluster
 - CPU: 2 Cores per server
 - Memory: 8GB per server

**Comment by joe-elliott** [comment]
Do you know how large your trace is? Do you have a max trace size configured?

The [CLI has a tool](https://grafana.com/docs/tempo/latest/operations/tempo_cli/#query-blocks-command) to download the summary of a very large trace directly from the backend blocks:

```
tempo-cli query trace-summary <trace-id> <tenant-id> --backend=<gcs|s3|whatever> --bucket=<my bucket name>
```

**Comment by edgarkz** [comment]
Same here
I have configured GOMEMLIMIT on querier and also have global max_bytes_per_trace set to 25000000 (25mb)
The only solution for me was to increase queries instances count and memory limits

**Comment by JustNZ** [comment]
Hey @joe-elliott ,
so that is the resul of my tempo-cli execution:

```
total blocks to search:  169
....................................0.................................................................100....................................................................Number of blocks: 169
Span count: 602299
Trace size: 245134713 B
Trace duration: 606679 seconds
Root service name:
Root span info:
No root span found
top frequent service.names:
[application    ]
```

and I have the following overrides configured inside tempo with the max trace size:
```
overrides:
  defaults:
    read:
      max_bytes_per_tag_values_query: 50000000
    metrics_generator:
      processors: [service-graphs, span-metrics]
      forwarder:
        queue_size: 500
    global:
      max_bytes_per_trace: 50000000
```

**Comment by edgarkz** [comment]
@JustNZ I think you have issues with tracing rootid or parent services.
600k span trace is really huge one..  make sure your services do start each request with unique root id and downstream it to other services

**Comment by JustNZ** [comment]
@edgarkz ,
yeah I know and I'm currently trying to make the grafana-agent aware to drop those traces so that they are not sent to tempo.
But anyway I would have expected that tempo says "trace to large" or something like this rather than running out of memory

**Comment by joe-elliott** [comment]
I agree Tempo should handle this better. We recently added better support for enforcing the max trace size on the query path, but it seems you are on 2.3.1 which should have those changes.

Can you share the output of the [tempo-cli analyse blocks](https://grafana.com/docs/tempo/latest/operations/tempo_cli/#analyse-blocks) command? If you have some very large attributes it might be impacting dictionary sizes in the Parquet blocks. We could use dedicated columns to improve query times and reduce memory usage.

**Comment by JustNZ** [comment]
So this is the output of the block analyse:
```
Top 15 span attributes by size
name: Command                      size: 4.4 MB   (32.94%)
name: host                   size: 3.1 MB   (23.23%)
name: Command_Class                size: 2.5 MB   (18.56%)
name: stage                  size: 1.9 MB   (14.20%)
name: instance               size: 691 kB   (5.16%)
name: grafana_agent.component_id   size: 184 kB   (1.38%)
name: component                    size: 166 kB   (1.24%)
name: http.user_agent              size: 134 kB   (1.00%)
name: net.peer.name                size: 63 kB    (0.47%)
name: sampler.type                 size: 54 kB    (0.41%)
name: net.host.name                size: 26 kB    (0.20%)
name: http.route                   size: 19 kB    (0.15%)
name: transport                    size: 19 kB    (0.15%)
name: net.sock.peer.addr           size: 19 kB    (0.14%)
name: Job Command                  size: 19 kB    (0.14%)
Top 8 resource attributes by size
name: host.name                     size: 882 kB   (33.89%)
name: opencensus.exporterversion    size: 833 kB   (32.00%)
name: ip                            size: 588 kB   (22.59%)
name: process.runtime.description   size: 158 kB   (6.05%)
name: telemetry.sdk.name            size: 66 kB    (2.54%)
name: service.version               size: 36 kB    (1.37%)
name: telemetry.sdk.version         size: 30 kB    (1.17%)
name: telemetry.sdk.language        size: 10 kB    (0.39%)
```

**Comment by JustNZ** [comment]
Alright I added the parquet_dedicated_columns - thanks.

I think for now I'm good and I would assume this OOM behaviour will anyway be reviewed and fixed in the future.
If any research/output is required by me just say so.

**Comment by savar** [comment]
We see a similar situation that we have a service (we know we have) which is a long running service and is creating one huge trace.

Yet even though we have the `max_bytes_per_trace` set to 5 MB, the ingester seem to not really deal with this correctly.
Checking the code it looks like a the bytes are just an in-memory thing summing up the overall thing per ingester instance.

That can create issues as the trace can get new spans ingested on different occasions like:
* re-deployments of ingesters
* restarts due to errors (OOM, ...)
* autoscaling ingesters as the consistent hash is redistributing at least some parts of the trace IDs so the distributor might start sending the traceID to a new ingester which has no knowledge about it

I am not sure if the compactor "could" help there because I am not sure from the code how the compactor is being executed and if this is compacting across all blocks or just within a block or between some blocks or whatever. But our trace was going over almost 5 days.

```
tempo-cli -c ~/tmp/parquet-cli/tempo.yml query trace-summary 3d05ebd1394c6c2f16ae48e5c3927a69 single-tenant                                                                                 
total blocks to search:  381
....0.................................................................................................100....................................................................................................200....
................................................................................................300................................................................................Number of blocks: 109 
Span count: 264452 
Trace size: 333958065 B 
Trace duration: 388437 seconds 
Root service name:  
Root span info:
No root span found
top frequent service.names: 
[our-service    ]
```

the JSON file downloaded via `tempo-cli` was then 1.1 GB in size which is obviously killing our queriers no matter what if we allow for it to retrieve it all (setting the `max_bytes_per_traceid` temporarily very high on the querier itself) and will still die if there is not at least >6Gi RAM which is weird on it's own because I would expect it to break of searches if the intermittent results already surpass the (in our case) 5Mi limit.
Not sure if this is due to too many `parallel` queries which load already so much data which will kill it or how to prevent this from happening.

Is there any plan to change something there or do you have any suggestions how we could prevent the querier to die even if we kind of get these metrics inside the blocks?

**Comment by joe-elliott** [comment]
> Yet even though we have the max_bytes_per_trace set to 5 MB, the ingester seem to not really deal with this correctly.

Unfortunately it's nearly impossible to perfectly enforce this limit at ingestion time. If you receive 4MB today for a trace id you'd have to review your entire retention to see if that trace id exists anywhere else in order to confirm if that 4MB exceeds the configured limit. This just isn't possible at scale.

> I am not sure if the compactor "could" help there ...

When compactors encounter traces that exceed the max bytes they do partially drop the trace to keep it under the configured max. This can be seen in the metric:

```
tempo_discarded_spans_total{reason="trace_too_large_to_compact"}
```

This is not perfect though b/c it only occurs when a compactor combines a trace. We are considering a compaction strategy which more aggressively attempts to de-dupe traces which would help a bit here.

> the JSON file downloaded via tempo-cli was then 1.1 GB in size which is obviously killing our queriers 

The query path does also have support for attempting to drop traces that are too large added in 2.3:

https://github.com/grafana/tempo/blob/5b739f8675cba6173b466ba6839805a8d5bedc94/CHANGELOG.md?plain=1#L130

Do your queriers/query-frontends have access to the limits? In extreme cases we have still seen OOMs but this has helped a lot on our side.

**Comment by savar** [comment]
> The query path does also have support for attempting to drop traces that are too large added in 2.3:
> 
> https://github.com/grafana/tempo/blob/5b739f8675cba6173b466ba6839805a8d5bedc94/CHANGELOG.md?plain=1#L130
> 
> Do your queriers/query-frontends have access to the limits? In extreme cases we have still seen OOMs but this has helped a lot on our side.

I have to check again on Monday. I think we just upgraded to 2.3 (from 2.2) so I am not 100% sure if I did all the testing consistently on both versions.

I remember that it was telling me the trace is too large when using the querier "debug" api (https://grafana.com/docs/tempo/latest/api_docs/#query `/querier/api/traces/<traceid>/...`) but if I remember correctly we needed to increase the memory on the querier from 2Gi to 6Gi so that it was able to tell us that the trace was > 5Mi.

Again, I am not 100% sure anymore it worked before 2.3 at all and I will test again on Monday if I can get it to respond properly with 2Gi memory limits and 5Mi `max_bytes_per_trace` setting and will report back.

**Comment by savar** [comment]
Tested it again, version 2.3.1 of tempo. The same query ID as said before (so same data in the backend).

**Using the querier debug api:**
```sh
curl -v localhost:3100/querier/api/traces/3d05ebd1394c6c2f16ae48e5c3927a69?mode=blocks                                                                                                      
* Host localhost:3100 was resolved.                                                                                                                                                                                 
* IPv6: ::1                                                                                                                                                                                                         
* IPv4: 127.0.0.1                                                                                                                                                                                                   
*   Trying [::1]:3100...                                                                                                                                                                                            
* Connected to localhost (::1) port 3100                                                                                                                                                                            
> GET /querier/api/traces/3d05ebd1394c6c2f16ae48e5c3927a69?mode=blocks HTTP/1.1
> Host: localhost:3100                                                                                    
> User-Agent: curl/8.5.0           
> Accept: */*           
>                
* Empty reply from server
* Closing connection                    
curl: (52) Empty reply from server
```

The querier has a limit on Memory of **2Gi**. It is getting OOM killed by kubernetes as it grows to more than the 2Gi.

**Doing the query against the query-frontend:**
```sh
curl -v localhost:3100/api/traces/3d05ebd1394c6c2f16ae48e5c3927a69
* Host localhost:3100 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:3100...
* Connected to localhost (::1) port 3100
> GET /api/traces/3d05ebd1394c6c2f16ae48e5c3927a69 HTTP/1.1
> Host: localhost:3100
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< Date: Mon, 12 Feb 2024 10:07:25 GMT
< Content-Length: 129
< 
2 errors occurred:
        * rpc error: code = Canceled desc = context canceled
        * rpc error: code = Canceled desc = context canceled


* Connection #0 to host localhost left intact
```
and I can see that one of the querier pods died due to OOMkilled.

The question is: is this expected, that a limit of **5Mi** on traces with blocks being around **50Mi** big, the querier dies due to OOM? Maybe we do query too many in parallel (not sure if we can really configure that), so that the memory is already consumed before it even can start summing it up properly? The referenced [MR](https://github.com/grafana/tempo/issues/2935) wouldn't suggest that, but I didn't check it in detail.

Even 6Gi doesn't work but with 16Gi we were able to query it. It still seems very off to us. Any idea/advice what to do here?

**Comment by joe-elliott** [comment]
It's possible that a querier will have to do more work then is suggested by the 330Mi. This trace is split across a large number of rows and row groups and will require the loading of many columns. Trace jobs are also divided up at the block level so it seems that at least one block is requiring quite a bit of work from the queriers to retrieve.

This may or may not help but you can increase the trace shards which will make each job smaller:
```
query_frontend:
    trace_by_id:
        query_shards: 1000
```

We also default hedging to "on" in the frontend for trace by id. I think this is a mistake we should correct, but I'd turn it off using:

```
query_frontend:
    trace_by_id:
        hedge_requests_at: 0
        hedge_requests_up_to: 0
```

Another thing we we can check is your column sizes. Can you run the [analyse blocks](https://grafana.com/docs/tempo/latest/operations/tempo_cli/#analyse-blocks) command against your backend? We may be able to find some optimizations with dedicated columns.

**Comment by savar** [comment]
Thanks for taking your time!

The analyze gives me back that:

```
Top 15 span attributes by size
name: thread.name            size: 34 MB    (20.44%)
name: db.statement           size: 27 MB    (16.04%)
name: db.connection_string   size: 14 MB    (8.22%)
name: net.peer.name          size: 12 MB    (7.02%)
name: http.target            size: 12 MB    (6.94%)
name: code.namespace         size: 9.6 MB   (5.78%)
name: http.user_agent        size: 8.9 MB   (5.37%)
name: net.host.name          size: 7.9 MB   (4.75%)
name: http.route             size: 7.4 MB   (4.47%)
name: net.sock.peer.addr     size: 6.8 MB   (4.10%)
name: net.transport          size: 3.8 MB   (2.27%)
name: code.function          size: 3.4 MB   (2.08%)
name: db.name                size: 2.8 MB   (1.71%)
name: db.user                size: 2.7 MB   (1.63%)
name: db.sql.table           size: 2.7 MB   (1.62%)
Top 15 resource attributes by size
name: process.command_line          size: 762 MB   (54.34%)
name: container.id                  size: 86 MB    (6.16%)
name: process.runtime.description   size: 71 MB    (5.09%)
name: host.name                     size: 59 MB    (4.18%)
name: process.executable.path       size: 51 MB    (3.61%)
name: k8s.pod.start_time            size: 39 MB    (2.80%)
name: node_name                     size: 38 MB    (2.71%)
name: k8s.node.name                 size: 38 MB    (2.71%)
name: process.runtime.name          size: 36 MB    (2.60%)
name: k8s.deployment.name           size: 36 MB    (2.56%)
name: instance                      size: 35 MB    (2.49%)
name: app                           size: 34 MB    (2.44%)
name: os.description                size: 31 MB    (2.21%)
name: telemetry.sdk.name            size: 18 MB    (1.25%)
name: k8s.pod.ip                    size: 16 MB    (1.15%)
```

I read about optimizations here. I am also happy to apply them, but I am still puzzled why the system doesn't cancel any search as soon as it detects that it already breached the max_size setting instead of loading all blocks.

I tried first this:

```yaml
  query_frontend:
      trace_by_id:                                                                                                                                                                                                                                                                         
        hedge_requests_at: 2s                                                                                                                                                                                                                                                              
        hedge_requests_up_to: 2                                                                                                                                                                                                                                                            
        query_shards: 50                                                                                                                                                                                                                                                                   
        concurrent_shards: 5
```

hoping that it is kind of not using too many shards in parallel to get this done quicker, but then all 3 queries actually crash

```
tempo-querier-fcc55c69b-bxfvn              0/1     CrashLoopBackOff   10 (88s ago)   22h
tempo-querier-fcc55c69b-qmp4x              0/1     CrashLoopBackOff   10 (87s ago)   22h
tempo-querier-fcc55c69b-rk49d              0/1     CrashLoopBackOff   10 (96s ago)   22h
```

with OOM killed pods.. the querier itself didn't complain though (as a response) and nothing logged.

Same happens with

```yaml
query_frontend:
  trace_by_id:
    hedge_requests_at: 0s
    hedge_requests_up_to: 0
    query_shards: 1000
```

Changing the queriers to limits of 10Gi of RAM will at least allows the querier to die because then this one has not enough memory anymore.

```
tempo-query-frontend-5fb758674b-g86md      1/1     Running   1 (12m ago)   12m
tempo-query-frontend-5fb758674b-g86md      0/1     OOMKilled   1 (12m ago)   12m
tempo-query-frontend-5fb758674b-g86md      1/1     Running     2 (1s ago)    12m
```

```
> GET /api/traces/3d05ebd1394c6c2f16ae48e5c3927a69 HTTP/1.1
> Host: localhost:3100
> User-Agent: curl/8.5.0
> Accept: */*
> 
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

But our memory limit on the query-frontend is also 200Mi and the CPU is also at 50m which is probably much too small.

Setting this to 100m CPU and 1Gi of RAM now gives me this:

```
> GET /api/traces/3d05ebd1394c6c2f16ae48e5c3927a69 HTTP/1.1
> Host: localhost:3100
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< Date: Tue, 13 Feb 2024 09:52:38 GMT
< Content-Length: 124
< 
rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4424578 vs. 4194304)
```

which is weird that this is a 500, but also the logs shows that it never aborts any of the queries:

```
{"caller":"server.go:1511","duration":"1m35.915113488s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (7749653 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:24.12861836Z"}
{"caller":"server.go:1511","duration":"1m38.42462102s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (6635641 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:26.638095293Z"}
{"caller":"server.go:1511","duration":"1m38.517341622s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (8477961 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:26.730904193Z"}
{"caller":"server.go:1511","duration":"1m38.519282684s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (5301365 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:26.730984891Z"}
{"caller":"server.go:1511","duration":"1m33.476042269s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4857152 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:28.549451725Z"}
{"caller":"server.go:1511","duration":"1m33.506494582s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4925433 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:28.612414304Z"}
{"caller":"server.go:1511","duration":"1m33.854981623s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (7761608 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:28.960776548Z"}
{"caller":"server.go:1511","duration":"1m33.897388101s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4340560 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:29.003125526Z"}
{"caller":"server.go:1511","duration":"1m33.897617996s","err":"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (8342291 vs. 4194304)","level":"warn","method":"/frontend.Frontend/Process","msg":"gRPC","ts":"2024-02-13T09:52:29.003289823Z"}
... (more in the logs)
{"caller":"server.go:2136","level":"warn","msg":"GET /api/traces/3d05ebd1394c6c2f16ae48e5c3927a69 (500) 27.686256387s Response: \"rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4424578 vs. 4194304)\\n\" ws: false; Accept: */*; User-Agent: curl/8.5.0; ","traceID":"711191286442939b","ts":"2024-02-13T09:52:38.261918345Z"}
```

Even increasing the memory and CPU on the frontend-querier is not changing that behaviour.
Not sure what to do next, except throwing memory/cpu on this issue. Still feels wrong with a 5Mi limit per trace.

**Comment by joe-elliott** [comment]
> The analyze gives me back that:

I'd recommend taking your top 5 or so attributes at the resource/span level and adding them to [dedicated columns](https://grafana.com/blog/2024/01/22/accelerate-traceql-queries-at-scale-with-dedicated-attribute-columns-in-grafana-tempo/)

> I am still puzzled why the system doesn't cancel any search as soon as it detects that it already breached the max_size setting instead of loading all blocks.

The reasons that a 330MB trace will require more memory to return are complex. Two reasons that come to mind:

1) consider that the querier is attempting many jobs at once, so even if a single job locally recognizes it's loading too much data it may be one of 10 or 20 different in flight jobs pulling data for the trace.
2) Parquet memory consumption is difficult to predict. To load a value from a page you often have to load the entire dictionary for the rowgroup to decode the column. Loading a 5Mi trace from a file may allocate considerably more than 5Mi while decoding the row from Parquet.

**Comment by savar** [comment]
Thanks. We will check into that and report back. But this may take a moment, I would not say this is solving the issue here in general though, so sorry if we took over the thread too much :disappointed: .

**Comment by joe-elliott** [comment]
>  so sorry if we took over the thread too much

No worries. I think there was good information here that others can learn from. We want to improve this area (obviously) and documenting some of the pain points is helpful.

Oh, I thought of a #3 :)

3) All size measurements of a trace in Tempo are of the uncompressed proto. This is because we ingest proto and historically stored it in this form. When reading a trace out of parquet it is extremely difficult to estimate the size that it will be in proto. We attempt some estimates, but they are not great. Ultimately the only way to know if a trace _is_ greater than the requested size is to convert it to proto and calculate the size. This, of course, requires quite a bit of small objects which taxes the heap and GC.
