### ISSUE TITLE
Add Audit Logs to the User Configurable API

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#3775]
Create audit logs for the user configurable API. Log the current value, value being saved and any additional information to help debug changes.

cc @kvrhdn to add details

**Comment by Manish-Giri** [comment]
Interested in taking this up, if there are any further details that can be added!

**Comment by kvrhdn** [comment]
We should already be logging some of this information in the API layer. For example when storing new limits: https://github.com/grafana/tempo/blob/main/modules/overrides/userconfigurable/api/api.go#L104

We currently log timestamp, tenant, the new value and the new version. When we are updating we also log the current version and value.
Is there anything else you would like to see? We could also log stuff like IP address and any headers, but I'm not sure how valuable that is since Tempo is most often deployed behind a gateway.

Finding these logs should be straightforward with Loki:
```
{namespace=~"tempo.*"} |= "component=overrides-api" != "method=GET"
```

![Untitled](https://github.com/grafana/tempo/assets/7748404/bbb36e64-e75d-4564-9c57-4d4f379e2d6d)

**Comment by joe-elliott** [comment]
> When we are updating we also log the current version and value.

@kvrhdn for clarity, on a successful update we log both the current data and the new data?

**Comment by kvrhdn** [comment]
> > When we are updating we also log the current version and value.
> 
> @kvrhdn for clarity, on a successful update we log both the current data and the new data?

We only do so when we are updating the value through a PATCH operation. For POST requests we just store the value and don't retrieve the current value.

For store operations (POST):
- ✍🏻 we log the incoming data and version supplied by caller
- we send the data to the backend (which will validate the version is the most recent)
- ✍🏻 afterwards we log the stored data, the version and the new version

For updates (PATCH):
- we fetch the limits for the backend
- ✍🏻 we log current limits, version and the received patch
- if the patch is applied successfully, we send the data to the backend
- ✍🏻 afterwards we log the stored data, the version and the new version

So POST and PATCH will log slightly different data. We could maybe make this more consistent and verbose? We could, for instance, always log the current version, even for POST request. This would require an additional fetch request from the backend which is negligible honestly.

We also recommend to use versioning on the backend, so depending on how long your backend saves versions you can also use those to look through the history.
