### ISSUE TITLE
TraceQL Metrics: { false } | rate() returns data

### ISSUE THREAD

**Issue by joe-elliott** [grafana/tempo#3806]
**Describe the bug**
The query

```
{ false } | rate()
```

returns data even though `{ false }` should match nothing:

![image](https://github.com/grafana/tempo/assets/2272392/8ab049bb-90a1-4ca6-bee7-323c26aa22eb)

**Comment by mdisibio** [comment]
This is likely the optimization to remove the second pass in https://github.com/grafana/tempo/blob/main/pkg/traceql/engine_metrics.go#L598  It's not detecting the reason to keep the second pass, which is the evaluation of `false` and would reject all spans.

At first glance I think this is limited to falsey static statements that don't inspect any data.  If there was a column condition in there it should work as expected, because that would be pushed down to storage.   Probably worth capturing this case further up in the query-frontend.

**Comment by ndk** [comment]
Some observations:

1. `{resource.service.name="A"} | rate()` - no metrics (all is filtered out, as expected because "A" does not exist).
2. `{resource.service.name!="A"} | rate()` - all metrics (no filtering, as expected because "A" does not exist).
3. `{.service.name="A"} | rate()` - all metrics (unexpected, should be filtered out like in case 1).
4. `{.service.name!="A"} | rate()` - all metrics (unexpected, should filter out all metrics with `.service.name="A",` even though "A" does not exist).
5. `{resource.service.name="auth-service"} | rate()` - only `auth-service` metrics (expected behavior).
6. `{resource.service.name!="auth-service"} | rate()` - all metrics except `auth-service` ones (expected behavior).
7. `{.service.name1="auth-service"} | rate()` - all metrics (unexpected, should behave like case 8).
8. `{resource.service.name1="auth-service"} | rate()` - no metrics (expected, because `service.name1` does not exist).

I'm not very strong in TraceQL, so these are my assumptions. As I understand, cases 3, 4, and 7 return incorrect results. Am I right? :)
