### ISSUE TITLE
[DOC] How can we generate clients code from Tempo GRPC API

### ISSUE THREAD

**Issue by xhyzzZ** [grafana/tempo#4447]
I would like to programmatically call gRPC API to execute streaming query according to the doc https://grafana.com/docs/tempo/latest/api_docs/#tempo-grpc-api. But it's not clear to me how can I generate for example java codes from the proto file.

**Comment by joe-elliott** [comment]
We are unable to help with generating java code from our proto definitions. You will need to reference the java docs.

Here is how we generate go from our proto:

https://github.com/grafana/tempo/blob/90b2ac5073a5ea8c85f128e2dffad1a2be340610/Makefile#L229

It is unfortunately quite complex due to the way we need to use OTel proto. Good luck!
