### ISSUE TITLE
Upgrade examples to grafana 8.1

### ISSUE THREAD

**Issue by hrodic** [grafana/tempo#870]
Right now only grafana 7.4 examples are provided.

**Comment by kvrhdn** [comment]
I believe all our examples besides [docker-compose/grafana7.4](https://github.com/grafana/tempo/tree/main/example/docker-compose/grafana7.4) use Grafana 7.5.7 because that was the latest version last time we went through them. That example is explicitly called `grafana7.4` because it's shows how to use Tempo with a version of Grafana older than 7.5.

If you are looking for a more recent Grafana example, check out the [docker-compose/local](https://github.com/grafana/tempo/tree/main/example/docker-compose/local) example, this uses Grafana 7.5.7.
I agree we should upgrade our examples to use Grafana 8.1.1, but for now you can replace the tag with 8.1.1. It should still work 🙂
