### ISSUE TITLE
Tempo doesn't work properly with Ceph

### ISSUE THREAD

**Issue by boniek83** [grafana/tempo#954]
**Describe the bug**
I'm using on-premise ceph instance as s3 storage and sometimes (queries for some ids work reliably well) I get following error when trying to query tempo through Grafana:

failed to get trace with id: 2aaf954c62359311 Status: 500 Internal Server Error Body: error querying store in Querier.FindTraceByID: error using pageFinder (single-tenant, 8ea3b1cf-bb32-4012-a1a1-ef50fcf273fc): error in range read from s3 backend, bucket: tempo, objName: single-tenant/8ea3b1cf-bb32-4012-a1a1-ef50fcf273fc/index: The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Environment:**
 - Infrastructure: on-premise Kubernetes 1.19
 - Deployment tool: helm chart (v0.9.14)

I would appreciate tips how to debug this further.

**Comment by joe-elliott** [comment]
AWS has very detailed documentation the proper way to sign requests:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html

This is a possible incompatibility between our [s3 client](https://github.com/minio/minio-go) and ceph. The only configuration option I'm aware of is here: 

https://github.com/grafana/tempo/blob/main/tempodb/backend/s3/config.go#L19

where you can tell the client to use the v2 signing strategy instead of v4 (default).

**Comment by boniek83** [comment]
That worked - no more errors like these! It would be great to update documentation as I believe Ceph is used commonly outside of cloud deployments.
